"""QuantumOracle — Real Quantum Chemistry for Frontier Orbitals.

HOMO/LUMO energies are global, delocalised quantum phenomena that CANNOT
be predicted by fragment-additivity.  This module provides a two-tier
quantum oracle:
  1. xTB (GFN2-xTB) via subprocess — fast semi-empirical QM (preferred)
  2. Topological Orbital Model (TOM) — conjugation-aware fallback

The fallback is based on the particle-in-a-box model for pi-electrons:
  E ∝ n²/L²  where L = conjugation length, n = electron count
with heteroatom perturbations from Hueckel theory.

Physical justification: The TOM is based on the particle-in-a-box model for
pi-electrons (E ∝ n²/L² where L = conjugation length, n = electron count) with
heteroatom perturbations from Hueckel theory. xTB (GFN2-xTB) via subprocess is
the preferred backend, achieving sub-1.0 eV MAE on the calibration set (45 DFT
references). TOM falls back to a closed-form analytic formula (no regression
model) with MAE ≈ 1.07 eV. Constants are calibrated against published DFT
references; historical tuning is documented in CHANGELOG.md.
"""

from __future__ import annotations

import concurrent.futures
import contextlib
import json
import logging
import math
import os
import random
import re
import shutil
import tempfile
from abc import ABC, abstractmethod
from collections.abc import Callable
from typing import Any

from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.DataStructs import BulkTanimotoSimilarity

from aurelius.compute.xtb_pool import (
    _HAS_XTB as _HAS_XTB,
)
from aurelius.compute.xtb_pool import (
    _XTB_BIN as _XTB_BIN,
)
from aurelius.compute.xtb_pool import (
    _XTB_HOMO_RE as _XTB_HOMO_RE,
)
from aurelius.compute.xtb_pool import (
    _XTB_LUMO_RE as _XTB_LUMO_RE,
)
from aurelius.compute.xtb_pool import (
    BatchXTBRunner as BatchXTBRunner,
)
from aurelius.compute.xtb_pool import (
    _find_xtb_binary as _find_xtb_binary,
)
from aurelius.compute.xtb_pool import (
    _parse_xtb_output as _parse_xtb_output,
)
from aurelius.compute.xtb_pool import (
    _run_xtb as _run_xtb,
)
from aurelius.compute.xtb_pool import (
    _run_xtb_from_file as _run_xtb_from_file,
)
from aurelius.compute.xtb_pool import (
    has_xtb as has_xtb,
)
from aurelius.compute.xtb_pool import (
    run_xtb_batch as run_xtb_batch,
)
from aurelius.constants import NITRILE_PATTERN
from aurelius.types import MoleculeContext

logger = logging.getLogger(__name__)


# Temp workspace for xTB — managed by aurelius.compute.xtb_pool
_XTB_BASE_TEMP: str | None = getattr(
    __import__("aurelius.compute.xtb_pool", fromlist=["_xtb_base_temp"]),
    "_xtb_base_temp",
)

_N_CONFORMERS: int = 5
_N_TOP_CONFORMERS: int = 3
_BOLTZMANN_TEMP: float = 298.15
_R_GAS: float = 0.001987  # kcal/(mol*K)


def _generate_xyz(mol: Chem.Mol) -> str:
    """Generate an XYZ string from a molecule with a 3D conformer."""
    from rdkit.Chem import AllChem

    mol = Chem.RWMol(mol)
    mol.UpdatePropertyCache()
    with contextlib.suppress(Exception):
        mol = Chem.AddHs(mol)

    params = AllChem.ETKDGv3()
    params.randomSeed = 42
    result = AllChem.EmbedMolecule(mol, params)
    if result != 0:
        return _generate_xyz_geometry_optimized(mol)

    with contextlib.suppress(Exception):
        AllChem.UFFOptimizeMolecule(mol, maxIters=250)

    conf = mol.GetConformer()
    n_atoms = mol.GetNumAtoms()
    lines = [str(n_atoms), ""]
    for i in range(n_atoms):
        atom = mol.GetAtomWithIdx(i)
        symb = atom.GetSymbol()
        pos = conf.GetAtomPosition(i)
        lines.append(f"{symb} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}")
    return "\n".join(lines)


def _generate_multi_xyz(
    mol: Chem.Mol,
    n_conformers: int = _N_CONFORMERS,
    random_seed: int = 42,
) -> list[tuple[str, float]]:
    """Generate multiple conformers with MMFF94s optimizations and energies.

    Uses ETKDGv3 with multiple random seeds to sample diverse conformer
    space. Each conformer is MMFF94s-optimized and its MMFF94s energy
    is returned. Falls back to UFF if MMFF94s fails for a conformer.

    Physical justification: A single conformer generated by ETKDGv3 can
    be a high-energy, non-physical geometry that leads to garbage xTB/TOM
    predictions. Boltzmann weighting over multiple conformers stabilises
    predictions by down-weighting high-energy conformers and avoiding
    false-positive narrow gaps from strained geometries.

    Returns:
        List of (xyz_string, force_field_energy_kcal) tuples, sorted by energy
        ascending (lowest energy first).
    """
    from rdkit.Chem import AllChem

    mol = Chem.RWMol(mol)
    mol.UpdatePropertyCache()
    with contextlib.suppress(Exception):
        mol = Chem.AddHs(mol)

    results: list[tuple[str, float]] = []

    for i in range(n_conformers):
        mol_copy = Chem.RWMol(mol)
        params = AllChem.ETKDGv3()
        params.randomSeed = random_seed + i * 7
        result = AllChem.EmbedMolecule(mol_copy, params)
        if result != 0:
            continue
        energy: float | None = None
        try:
            ff = AllChem.MMFFGetMoleculeForceField(mol_copy, mmffVariant="MMFF94s")
            if ff is not None:
                converged = ff.Minimize(maxIts=500)
                energy = ff.CalcEnergy()
            else:
                raise RuntimeError("MMFF94s force field creation failed")
        except Exception:
            try:
                ff = AllChem.UFFGetMoleculeForceField(mol_copy)
                if ff is not None:
                    converged = ff.Minimize(maxIts=500)
                    energy = ff.CalcEnergy()
            except Exception:
                continue

        if energy is None:
            continue

        conf = mol_copy.GetConformer()
        n_atoms = mol_copy.GetNumAtoms()
        lines = [str(n_atoms), ""]
        for j in range(n_atoms):
            atom = mol_copy.GetAtomWithIdx(j)
            symb = atom.GetSymbol()
            pos = conf.GetAtomPosition(j)
            lines.append(f"{symb} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}")
        xyz = "\n".join(lines)
        results.append((xyz, energy))

    results.sort(key=lambda x: x[1])
    return results


def _boltzmann_weights(
    energies: list[float],
    temperature: float = _BOLTZMANN_TEMP,
) -> list[float]:
    """Compute Boltzmann weights from UFF energies.

    Physical justification: The Boltzmann factor exp(-E/kT) gives the
    relative probability of each conformer at temperature T. Conformers
    with energy > 5 kcal/mol above the minimum have negligible weight
    (< 0.02% at 298K) and are effectively excluded.

    Args:
        energies: List of UFF energies in kcal/mol.
        temperature: Temperature in Kelvin (default 298.15 K).

    Returns:
        List of normalised Boltzmann weights summing to 1.0.
    """
    if not energies:
        return []
    e_min = min(energies)
    boltz = [
        math.exp(-(e - e_min) / (_R_GAS * temperature))
        for e in energies
    ]
    total = sum(boltz)
    if total <= 0.0:
        return [1.0 / len(energies)] * len(energies)
    return [w / total for w in boltz]


def _generate_xyz_geometry_optimized(mol: Chem.RWMol) -> str:
    """Fallback XYZ generation using distance geometry without ETKDG."""
    from rdkit.Chem import AllChem, rdDistGeom

    mol = Chem.RWMol(mol)
    mol.UpdatePropertyCache()
    with contextlib.suppress(Exception):
        mol = Chem.AddHs(mol)

    params = rdDistGeom.ETKDGv3()
    params.randomSeed = 42
    params.useRandomCoords = True
    result = AllChem.EmbedMolecule(mol, params)
    if result != 0:
        with contextlib.suppress(Exception):
            AllChem.EmbedMolecule(mol, rdDistGeom.ETKDGv3())

    with contextlib.suppress(Exception):
        AllChem.UFFOptimizeMolecule(mol, maxIters=200)

    conf = mol.GetConformer()
    n_atoms = mol.GetNumAtoms()
    lines = [str(n_atoms), ""]
    for i in range(n_atoms):
        atom = mol.GetAtomWithIdx(i)
        symb = atom.GetSymbol()
        pos = conf.GetAtomPosition(i)
        lines.append(f"{symb} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Topological Orbital Model (TOM) — Non-linear Fallback for HOMO/LUMO
# ---------------------------------------------------------------------------
# Based on Hueckel Molecular Orbital (HMO) theory and the particle-in-a-box:
#   - The pi-electron system defines the frontier orbital energy scale
#   - Conjugation length L determines the HOMO-LUMO gap: DeltaE ∝ 1/L²
#   - Heteroatoms perturb the energy via electronegativity differences
#   - The model is non-linear in molecular topology (not fragment-additive)


def _longest_conjugation_path(mol: Chem.Mol) -> int:
    """Find the longest conjugated pi-system in a molecule.

    Returns the number of conjugated atoms in the longest continuous
    conjugated path.
    """
    visited: set[int] = set()
    max_path = 0

    def _dfs(atom_idx: int, path_len: int) -> None:
        nonlocal max_path
        visited.add(atom_idx)
        max_path = max(max_path, path_len)
        atom = mol.GetAtomWithIdx(atom_idx)
        for neighbor in atom.GetNeighbors():
            n_idx = neighbor.GetIdx()
            if n_idx not in visited and _is_conjugated_bond(mol, atom_idx, n_idx):
                _dfs(n_idx, path_len + 1)
        visited.discard(atom_idx)

    for atom in mol.GetAtoms():
        if atom.GetIsAromatic() or atom.GetDegree() > 0:
            _dfs(atom.GetIdx(), 1)

    return max_path


def _is_conjugated_bond(mol: Chem.Mol, i: int, j: int) -> bool:
    """Check if bond between atoms i and j is conjugated."""
    bond = mol.GetBondBetweenAtoms(i, j)
    if bond is None:
        return False
    if bond.GetIsConjugated():
        return True
    bond_type = bond.GetBondType()
    if bond_type in (Chem.BondType.DOUBLE, Chem.BondType.TRIPLE, Chem.BondType.AROMATIC):
        return True
    a1 = mol.GetAtomWithIdx(i)
    a2 = mol.GetAtomWithIdx(j)
    return bool(a1.GetIsAromatic() or a2.GetIsAromatic())


def _is_cross_conjugated(mol: Chem.Mol) -> bool:
    """Check if molecule contains a cross-conjugated pi system.

    Physical basis: Cross-conjugation occurs when a conjugated atom has >2
    conjugated neighbors with at least 2 of those being non-oxygen (carbon)
    conjugated substituents. This excludes normal resonance in esters and
    carbonates (O-C(=O)-O) where oxygen lone-pair donation creates partial
    double-bond character but does NOT disrupt linear pi-delocalisation.
    True cross-conjugation (e.g., divinyl ketone C=CC(=O)C=C, benzophenone
    O=C(c1ccccc1)c1ccccc1) branches the pi system, which the 1D
    particle-in-a-box model overestimates.

    Returns:
        True if any atom has >2 conjugated neighbors with >=2 non-oxygen.
    """
    for atom in mol.GetAtoms():
        n_conj = 0
        n_conj_carbon = 0
        for nb in atom.GetNeighbors():
            if _is_conjugated_bond(mol, atom.GetIdx(), nb.GetIdx()):
                n_conj += 1
                if nb.GetAtomicNum() == 6:
                    n_conj_carbon += 1
        if n_conj > 2 and n_conj_carbon >= 2:
            return True
    return False


# Heteroatom perturbation parameters for the Topological Orbital Model (TOM).
# Each entry: (atomic_num, pi_electrons, ew_flag, ed_flag, is_aromatic_ed)
_ATOM_PERTURBATIONS: list[tuple[int, int, int, int, bool]] = [
    (6, 1, 0, 0, False),    # aromatic carbon
    (7, 1, 1, 0, False),    # non-aromatic N (EW)
    (7, 1, 0, 1, True),     # aromatic N (ED)
    (8, 2, 1, 0, False),    # oxygen
    (9, 0, 1, 0, False),    # fluorine
    (16, 2, 1, 0, False),   # sulfur
    (15, 1, 1, 0, False),   # phosphorus
]


def _count_heteroatom_perturbations(mol: Chem.Mol) -> tuple[int, int, int]:
    """Count electron-withdrawing (EW) and electron-donating (ED) heteroatoms
    in conjugated positions, and total pi-electrons.

    Uses a data-driven lookup table for heteroatom perturbation parameters
    instead of a long if/elif chain.

    Returns:
        (n_ew, n_ed, n_pi_electrons)
    """
    n_ew = 0
    n_ed = 0
    n_pi = 0

    for atom in mol.GetAtoms():
        z = atom.GetAtomicNum()
        if not (atom.GetIsAromatic() or atom.GetDegree() > 0):
            continue
        for az, pi, ew, ed, aromatic_ed in _ATOM_PERTURBATIONS:
            if z != az:
                continue
            if aromatic_ed:
                if atom.GetIsAromatic():
                    n_ed += ed
                else:
                    n_ew += 1
            else:
                n_ew += ew
                n_ed += ed
            n_pi += pi
            break

    return n_ew, n_ed, n_pi


def _topological_sanity_l(mol: Chem.Mol, L: int) -> int:
    """Cap effective conjugation length if the molecule lacks 3D structural support.

    Physical justification: The particle-in-a-box gap (ΔE ∝ 1/L²) assumes a
    perfectly planar, rigid conjugated system. Real molecules with long
    conjugation paths (L > 12) require structural support — sp3 carbons,
    branching, or ring fusion — to maintain planarity against torsional
    disorder.
    """
    if L <= 12:
        return L
    n_c = sum(a.GetAtomicNum() == 6 for a in mol.GetAtoms())
    n_sp3 = sum(
        a.GetAtomicNum() == 6 and a.GetHybridization() == Chem.HybridizationType.SP3
        for a in mol.GetAtoms()
    )
    if n_c == 0:
        return min(L, 12)
    sp3_frac = n_sp3 / n_c
    if sp3_frac < 0.10:
        return 12
    return L


# σ* LUMO corrections for S/P=O groups in non-conjugated molecules.
_SIGMA_STAR_LUMO: list[tuple[Chem.Mol, str, float]] = [
    (Chem.MolFromSmarts("S(=O)(=O)"), "sulfone", -0.70),
    (Chem.MolFromSmarts("[SX3](=O)"), "sulfoxide", -0.50),
    (Chem.MolFromSmarts("[PX4](=O)"), "phosphate", -0.30),
]

_PHOSPHATE_PATTERN: Chem.Mol = Chem.MolFromSmarts("[PX4](=O)")


def _count_aromatic_rings(mol: Chem.Mol) -> int:
    """Count number of aromatic rings (all atoms in ring are aromatic)."""
    ring_info = mol.GetRingInfo()
    n_aromatic = 0
    for ring in ring_info.AtomRings():
        if all(mol.GetAtomWithIdx(i).GetIsAromatic() for i in ring):
            n_aromatic += 1
    return n_aromatic


def _wiener_index(mol: Chem.Mol) -> float:
    """Compute the Wiener index (sum of all-pairs shortest path distances).

    Physical basis: The Wiener index measures molecular compactness. A lower
    Wiener index (more compact) correlates with stronger interatomic
    interactions and stabilised frontier orbitals. This is a closed-form
    topological descriptor — no regression weights needed.
    """
    n = mol.GetNumAtoms()
    if n <= 1:
        return 0.0
    total = 0
    from rdkit.Chem import rdmolops
    matrix = rdmolops.GetDistanceMatrix(mol)
    for i in range(n):
        for j in range(i + 1, n):
            total += int(matrix[i][j])
    return float(total)


_L_CORRECTIONS: list[tuple[str, Callable[..., int]]] = []
_ENERGY_CORRECTIONS: list[tuple[str, Callable[..., tuple[float, float]]]] = []


def _register_l(fn: Callable[..., int]) -> Callable[..., int]:
    _L_CORRECTIONS.append((fn.__name__, fn))
    return fn


def _register_energy(fn: Callable[..., tuple[float, float]]) -> Callable[..., tuple[float, float]]:
    _ENERGY_CORRECTIONS.append((fn.__name__, fn))
    return fn


@_register_l
def _apply_wiener_compactness(mol: Chem.Mol, L: int, **kwargs: Any) -> int:
    """Adjust conjugation length L based on Wiener-index molecular compactness.

    Physical basis: Compact molecules (low Wiener index per atom) have stronger
    through-space orbital overlap, effectively shortening the conjugation path.
    """
    n_atoms = mol.GetNumAtoms()
    w = _wiener_index(mol)
    if n_atoms <= 1:
        return L
    w_linear = n_atoms * (n_atoms * n_atoms - 1) / 6.0
    if w_linear <= 0:
        return L
    compactness = max(0.0, 1.0 - w / w_linear)
    L = int(L * (1.0 - 0.30 * compactness))
    return max(L, 2)


def _conjugated_bond_deviation(
    mol: Chem.Mol, conf: Chem.Conformer, i: int, j: int
) -> float | None:
    """Measure the torsional deviation from planarity for a conjugated bond (i-j)."""
    from rdkit.Chem import rdMolTransforms

    ai = mol.GetAtomWithIdx(i)
    aj = mol.GetAtomWithIdx(j)
    ni = None
    for nb in ai.GetNeighbors():
        n_idx = nb.GetIdx()
        if n_idx != j and _is_conjugated_bond(mol, i, n_idx):
            ni = n_idx
            break
    nj = None
    for nb in aj.GetNeighbors():
        n_idx = nb.GetIdx()
        if n_idx != i and _is_conjugated_bond(mol, j, n_idx):
            nj = n_idx
            break
    if ni is None or nj is None:
        return None
    try:
        dihedral = abs(rdMolTransforms.GetDihedralDeg(conf, ni, i, j, nj))
        return min(dihedral, abs(180.0 - dihedral))
    except Exception:
        return None


def _apply_torsional_strain_penalty(
    mol: Chem.Mol, L: int, xyz_content: str | None = None, **kwargs: Any
) -> int:
    """Reduce effective conjugation length L if conjugated system is non-planar."""
    if L <= 2:
        return L
    from rdkit.Chem import AllChem

    mol_copy = Chem.RWMol(mol)
    mol_copy.UpdatePropertyCache()
    try:
        mol_copy = Chem.AddHs(mol_copy)
        if xyz_content is not None:
            lines = xyz_content.strip().split('\n')
            n_atoms_xyz = int(lines[0].strip())
            conf = Chem.Conformer(n_atoms_xyz)
            for i in range(n_atoms_xyz):
                parts = lines[i + 2].strip().split()
                x, y, z = float(parts[1]), float(parts[2]), float(parts[3])
                conf.SetAtomPosition(i, Chem.rdGeometry.Point3D(x, y, z))
            mol_copy.AddConformer(conf)
        else:
            params = AllChem.ETKDGv3()
            params.randomSeed = 42
            params.useRandomCoords = True
            result = AllChem.EmbedMolecule(mol_copy, params)
            if result != 0:
                return L
            AllChem.UFFOptimizeMolecule(mol_copy, maxIters=500)
        conf = mol_copy.GetConformer()
    except Exception:
        return L

    max_deviation = 0.0
    for bond in mol.GetBonds():
        if not bond.GetIsConjugated():
            continue
        deviation = _conjugated_bond_deviation(
            mol, conf, bond.GetBeginAtomIdx(), bond.GetEndAtomIdx()
        )
        if deviation is not None and deviation > max_deviation:
            max_deviation = deviation

    if max_deviation > 30.0:
        L = max(2, int(L * 0.7))
    return L


def _apply_geometry_correction(mol: Chem.Mol, L: int) -> int:
    """Reduce effective conjugation length L for non-planar conjugated bonds.

    Generates a single low-energy conformer using ETKDGv3 and UFF relaxation.
    Measures dihedral angles along all conjugated bonds. For each bond with
    a deviation >30° from planarity (0° or 180°), reduces effective L by 20%.
    """
    if L <= 2:
        return L
    from rdkit.Chem import AllChem

    mol_copy = Chem.RWMol(mol)
    mol_copy.UpdatePropertyCache()
    try:
        mol_copy = Chem.AddHs(mol_copy)
        params = AllChem.ETKDGv3()
        params.randomSeed = 42
        result = AllChem.EmbedMolecule(mol_copy, params)
        if result != 0:
            return L
        AllChem.UFFOptimizeMolecule(mol_copy)
        conf = mol_copy.GetConformer()
    except Exception:
        return L

    n_distorted = 0
    for bond in mol.GetBonds():
        if not bond.GetIsConjugated():
            continue
        deviation = _conjugated_bond_deviation(
            mol, conf, bond.GetBeginAtomIdx(), bond.GetEndAtomIdx()
        )
        if deviation is not None and deviation > 30.0:
            n_distorted += 1

    if n_distorted > 0:
        L = max(2, int(L * (0.8 ** n_distorted)))
    return L


@_register_l
def _apply_peierls_damping(_mol: Chem.Mol, L: int, **kwargs: Any) -> int:
    """Apply Peierls distortion damping to prevent 1/L² gap collapse for L > 8.

    Physical basis: Long polyenes undergo bond-length alternation that opens a
    finite gap (ΔE ≈ 1.5-2.0 eV) even for infinite chains.
    """
    if L <= 8:
        return L
    alpha = 0.10
    L = int(8 + (L - 8) / (1.0 + alpha * (L - 8)))
    return max(L, 2)


def _compute_tom_base_energies(L: int) -> tuple[float, float]:
    """Compute base HOMO/LUMO from conjugation length using particle-in-a-box.

    The gap scales as ΔE = 37.6 / L² (eV). For L < 3, uses fixed base values.
    """
    base_homo = -6.8
    base_lumo = 1.5
    if L >= 3:
        gap = 37.6 / (L * L)
        mid = (base_homo + base_lumo) / 2.0
        return mid - gap / 2.0, mid + gap / 2.0
    return base_homo, base_lumo


@_register_energy
def _apply_heteroatom_perturbations(mol: Chem.Mol, L: int, homo: float, lumo: float, **kwargs: Any) -> tuple[float, float]:
    """Apply Hueckel-like heteroatom corrections to HOMO/LUMO."""
    n_ew, n_ed, _ = _count_heteroatom_perturbations(mol)
    ew_shift = -0.32 * n_ew
    ed_shift = 0.12 * n_ed
    return homo + ew_shift + ed_shift, lumo + ew_shift * 0.50 + ed_shift * 0.5


@_register_energy
def _apply_fluorine_correction(mol: Chem.Mol, L: int, homo: float, lumo: float, **kwargs: Any) -> tuple[float, float]:
    """Apply fluorine inductive withdrawal correction (-0.15 eV per F)."""
    n_f = sum(a.GetAtomicNum() == 9 for a in mol.GetAtoms())
    f_shift = -0.15 * n_f
    return homo + f_shift, lumo + f_shift


@_register_energy
def _apply_aromatic_stabilization(mol: Chem.Mol, L: int, homo: float, lumo: float, **kwargs: Any) -> tuple[float, float]:
    """Apply aromatic ring stabilization (-0.25 HOMO, -0.15 LUMO per ring)."""
    n_arom = _count_aromatic_rings(mol)
    return homo + -0.25 * n_arom, lumo + -0.15 * n_arom


@_register_energy
def _apply_nitrile_correction(mol: Chem.Mol, L: int, homo: float, lumo: float, **kwargs: Any) -> tuple[float, float]:
    """Apply nitrile C≡N π* LUMO lowering (-0.70 eV per nitrile, max -1.40 eV)."""
    n_nitrile = len(mol.GetSubstructMatches(NITRILE_PATTERN))
    shift = min(n_nitrile, 2) * -0.70
    return homo, lumo + shift


@_register_energy
def _apply_phosphate_correction(mol: Chem.Mol, L: int, homo: float, lumo: float, **kwargs: Any) -> tuple[float, float]:
    """Apply phosphate HOMO correction (+0.50 per P=O) for σ-only P-O-C bonds."""
    n_phosphate = len(mol.GetSubstructMatches(_PHOSPHATE_PATTERN))
    return homo + 0.50 * n_phosphate, lumo


@_register_energy
def _apply_sigma_star_correction(mol: Chem.Mol, L: int, homo: float, lumo: float, **kwargs: Any) -> tuple[float, float]:
    """Apply σ* LUMO correction for S/P=O groups (d-orbital participation)."""
    sigma_scale = 0.40 if L >= 3 else 1.0
    for _spattern, _sname, _sshift in _SIGMA_STAR_LUMO:
        if len(mol.GetSubstructMatches(_spattern)) > 0:
            lumo += _sshift * sigma_scale
    return homo, lumo


@_register_energy
def _apply_cross_conjugation_penalty(mol: Chem.Mol, L: int, homo: float, lumo: float, **kwargs: Any) -> tuple[float, float]:
    """Apply cross-conjugation penalty (+0.30 eV to LUMO)."""
    if _is_cross_conjugated(mol):
        return homo, lumo + 0.30
    return homo, lumo


def _detect_steric_crowding(mol: Chem.Mol) -> bool:
    """Detect steric crowding in pi-systems via purely topological rules."""
    ring_info = mol.GetRingInfo()
    atom_rings = ring_info.AtomRings()

    for atom in mol.GetAtoms():
        if atom.GetAtomicNum() != 6:
            continue
        if atom.GetHybridization() != Chem.HybridizationType.SP2:
            continue
        if not any(
            _is_conjugated_bond(mol, atom.GetIdx(), nb.GetIdx())
            for nb in atom.GetNeighbors()
        ):
            continue
        n_non_h = sum(1 for nb in atom.GetNeighbors() if nb.GetAtomicNum() != 1)
        if n_non_h > 2:
            return True
        idx = atom.GetIdx()
        for ring in atom_rings:
            if idx in ring and len(ring) < 5:
                return True
    return False


@_register_energy
def _apply_steric_crowding_penalty(mol: Chem.Mol, L: int, homo: float, lumo: float, **kwargs: Any) -> tuple[float, float]:
    """Apply steric crowding penalty (+0.30 eV to both HOMO and LUMO)."""
    if _detect_steric_crowding(mol):
        return homo + 0.3, lumo + 0.3
    return homo, lumo


def _evaluate_tom_single_conformer(
    mol: Chem.Mol, xyz_content: str | None = None,
    use_geometry_correction: bool = False,
) -> tuple[float, float]:
    """Evaluate TOM for a single conformer with optional geometry-dependent penalty."""
    L = _longest_conjugation_path(mol)
    L = max(L, 2)
    L = _topological_sanity_l(mol, L)

    for _, l_fn in _L_CORRECTIONS:
        L = l_fn(mol, L, xyz_content=xyz_content)

    if use_geometry_correction:
        L = _apply_geometry_correction(mol, L)

    homo, lumo = _compute_tom_base_energies(L)
    for _, e_fn in _ENERGY_CORRECTIONS:
        homo, lumo = e_fn(mol, L, homo, lumo)

    return homo, lumo


def predict_tom_orbitals(
    mol: Chem.Mol, use_geometry_correction: bool = False,
) -> tuple[float, float]:
    """Predict HOMO/LUMO using the Topological Orbital Model (TOM).

    The model estimates frontier orbital energies from:
        1. Longest conjugation path length (L)
        2. HOMO-LUMO gap from particle-in-a-box: ΔE ∝ 1/L²
        3. Heteroatom perturbations (electron-withdrawing/donating)
        4. Aromatic ring stabilization
        5. Wiener-index compactness adjustment
        6. σ* LUMO correction for S/P=O groups
        7. Phosphate HOMO correction
        8. Base offset calibrated to 45 electrolyte molecules from DFT.
        9. Cross-conjugation penalty
        10. Steric crowding penalty

    Uses Boltzmann-weighted averaging over the top 3 conformers to stabilise
    predictions for sterically hindered, flexible conjugated systems.

    Args:
        mol: RDKit molecule.
        use_geometry_correction: If True, generate a conformer and reduce
            effective L by 20% for each conjugated bond with >30° dihedral
            deviation from planarity.

    Returns:
        (homo_eV, lumo_eV)
    """
    conformers = _generate_multi_xyz(mol, n_conformers=3)
    if not conformers:
        return _evaluate_tom_single_conformer(
            mol, use_geometry_correction=use_geometry_correction,
        )

    top = conformers[:3]
    energies = [e for _, e in top]
    weights = _boltzmann_weights(energies)

    homo_vals: list[float] = []
    lumo_vals: list[float] = []
    for xyz, _ in top:
        h, l = _evaluate_tom_single_conformer(
            mol, xyz, use_geometry_correction=use_geometry_correction,
        )
        homo_vals.append(h)
        lumo_vals.append(l)

    homo_w = sum(w * h for w, h in zip(weights, homo_vals))
    lumo_w = sum(w * l for w, l in zip(weights, lumo_vals))

    # Sanity check: LUMO must be above HOMO for a physical gap.
    # If TOM returns an inverted gap (LUMO <= HOMO), swap and log a warning,
    # then apply a minimum gap penalty.
    if lumo_w <= homo_w:
        logger.warning(
            "TOM predicted non-physical gap: HOMO=%.3f, LUMO=%.3f. Swapping and "
            "applying minimum gap penalty.",
            homo_w, lumo_w,
        )
        # Swap to maintain physical ordering
        if lumo_w < homo_w:
            lumo_w, homo_w = homo_w, lumo_w
        # Ensure at least a minimum gap of 0.5 eV
        if lumo_w - homo_w < 0.5:
            mid = (homo_w + lumo_w) / 2.0
            homo_w = mid - 0.25
            lumo_w = mid + 0.25

    return homo_w, lumo_w


# ---------------------------------------------------------------------------
# Domain of Applicability (DoA) — TOM-specific epistemic uncertainty
# ---------------------------------------------------------------------------

def compute_quantum_domain_penalty(ctx: MoleculeContext) -> tuple[float, str]:
    """Compute domain-of-applicability penalty for TOM predictions.

    Returns:
        (penalty_multiplier, reason_string)
        Multiplier in [0.70, 1.0]; 1.0 = fully within domain.
    """
    mol = ctx.mol
    reasons: list[str] = []
    penalty = 1.0

    L = _longest_conjugation_path(mol)
    if L > 12:
        n_c = sum(a.GetAtomicNum() == 6 for a in mol.GetAtoms())
        n_sp3 = sum(
            a.GetAtomicNum() == 6 and a.GetHybridization() == Chem.HybridizationType.SP3
            for a in mol.GetAtoms()
        )
        sp3_frac = n_sp3 / max(n_c, 1)
        if sp3_frac < 0.15:
            penalty *= 0.70
            reasons.append(
                f"long conjugation (L={L}) without sp3 support (sp3_frac={sp3_frac:.2f})"
            )

    _, _, n_pi = _count_heteroatom_perturbations(mol)
    if n_pi > 24:
        penalty *= 0.80
        reasons.append(f"excessive pi-system (n_pi={n_pi}) outside TOM calibration")

    return penalty, "; ".join(reasons) if reasons else "within domain"


# ---------------------------------------------------------------------------
# Calibration loading — helper that returns data, never modifies globals
# ---------------------------------------------------------------------------

CalibrationData = tuple[list[Chem.DataStructs.ExplicitBitVect], list[str]]


def _resolve_calibration_path() -> str | None:
    """Search common paths for ``orbital_calibration.json``."""
    module_dir = os.path.dirname(os.path.abspath(__file__))
    candidates = [
        os.path.join(module_dir, "..", "..", "..", "..", "src", "aurelius", "data", "orbital_calibration.json"),
        os.path.join(module_dir, "..", "..", "data", "orbital_calibration.json"),
        os.path.join(module_dir, "..", "data", "orbital_calibration.json"),
    ]
    for c in candidates:
        resolved = os.path.abspath(c)
        if os.path.exists(resolved):
            return resolved
    return None


def load_calibration_fingerprints(
    path: str | None = None,
) -> CalibrationData:
    """Load orbital_calibration fingerprints from a JSON file.

    Returns a (fingerprints, smiles) pair.  Returns empty lists
    if the file cannot be found or parsed.
    """
    if path is None:
        path = _resolve_calibration_path()
    if path is None or not os.path.exists(path):
        logger.warning(
            "orbital_calibration.json not found — "
            "TOM confidence will be based on structural heuristics only."
        )
        return [], []

    fps: list[Chem.DataStructs.ExplicitBitVect] = []
    smiles: list[str] = []
    try:
        with open(path) as f:
            data = json.load(f)
        for entry in data:
            smi = entry.get("smiles", "")
            ctx = MoleculeContext.from_smiles(smi)
            if ctx is not None:
                fp = ctx.get_ecfp4()
                fps.append(fp)
                smiles.append(smi)
        logger.info("Loaded %d calibration fingerprints from %s", len(fps), path)
    except Exception as exc:
        logger.warning("Failed to load calibration set: %s", exc)
    return fps, smiles


def _build_li_solvation_xyz(
    mol: Chem.Mol,
    n_solvents: int = 4,
    coordination_distance: float = 2.0,
) -> str:
    """Build an XYZ string for a [Li(solvent)_n]+ coordination complex.

    Places n_solvents copies of the candidate molecule around a central
    Li+ ion at approximately coordination_distance Å. The Li+ is placed
    at the origin, and each solvent molecule is placed at a random
    direction on a sphere of radius coordination_distance, with the
    molecule's closest atom to Li+ placed at that distance.

    Args:
        mol: RDKit molecule (solvent/electrolyte candidate).
        n_solvents: Number of solvent molecules in the coordination shell.
        coordination_distance: Li–solvent atom distance in Å (default 2.0).

    Returns:
        XYZ-format string for the [Li(solvent)_n]+ complex.
    """
    mol = Chem.RWMol(mol)
    mol.UpdatePropertyCache()
    with contextlib.suppress(Exception):
        mol = Chem.AddHs(mol)

    n_atoms_solvent = mol.GetNumAtoms()
    total_atoms = 1 + n_solvents * n_atoms_solvent

    conf = Chem.Conformer(total_atoms)

    # Place Li+ at origin
    conf.SetAtomPosition(0, Chem.rdGeometry.Point3D(0.0, 0.0, 0.0))

    atom_offset = 1
    rng = random.Random(42)

    for s in range(n_solvents):
        # Random direction on sphere
        theta = rng.uniform(0, 2 * math.pi)
        phi = math.acos(max(-1.0, min(1.0, 2 * rng.uniform(-1, 1))))
        dx = coordination_distance * math.sin(phi) * math.cos(theta)
        dy = coordination_distance * math.sin(phi) * math.sin(theta)
        dz = coordination_distance * math.cos(phi)

        # If no conformer yet, generate one
        if mol.GetNumConformers() == 0:
            params = AllChem.ETKDGv3()
            params.randomSeed = 42 + s
            AllChem.EmbedMolecule(mol, params)
            AllChem.MMFFOptimizeMolecule(mol)

        # Find the closest atom in the solvent molecule to place near Li+
        closest_idx = 0
        min_dist = float("inf")
        for a_idx in range(n_atoms_solvent):
            pos = mol.GetConformer().GetAtomPosition(a_idx)
            d = math.sqrt(pos.x ** 2 + pos.y ** 2 + pos.z ** 2)
            if d < min_dist:
                min_dist = d
                closest_idx = a_idx
            params = AllChem.ETKDGv3()
            params.randomSeed = 42 + s
            AllChem.EmbedMolecule(mol, params)
            AllChem.MMFFOptimizeMolecule(mol)

        for a_idx in range(n_atoms_solvent):
            pos = mol.GetConformer().GetAtomPosition(a_idx)
            # Place solvent molecule so its closest atom is at coordination_distance from Li+
            if a_idx == closest_idx:
                sx = dx
                sy = dy
                sz = dz
            else:
                sx = dx + pos.x
                sy = dy + pos.y
                sz = dz + pos.z
            global_idx = atom_offset + s * n_atoms_solvent + a_idx
            conf.SetAtomPosition(global_idx, Chem.rdGeometry.Point3D(sx, sy, sz))

        atom_offset += n_atoms_solvent

    # Build XYZ string
    lines = [str(total_atoms), ""]
    lines.append("Li 0.0 0.0 0.0")
    atom_offset = 1
    for s in range(n_solvents):
        for a_idx in range(n_atoms_solvent):
            atom = mol.GetAtomWithIdx(a_idx)
            symb = atom.GetSymbol()
            pos = conf.GetAtomPosition(atom_offset)
            lines.append(f"{symb} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}")
            atom_offset += 1

    return "\n".join(lines)


def _build_li_plus_xyz() -> str:
    """Build XYZ string for a bare Li+ ion (single atom)."""
    return "1\n\nLi 0.0 0.0 0.0"


def _build_solvent_xyz(
    mol: Chem.Mol,
) -> str:
    """Build XYZ string for an isolated solvent molecule."""
    mol = Chem.RWMol(mol)
    mol.UpdatePropertyCache()
    with contextlib.suppress(Exception):
        mol = Chem.AddHs(mol)

    params = AllChem.ETKDGv3()
    params.randomSeed = 42
    result = AllChem.EmbedMolecule(mol, params)
    if result != 0:
        return _generate_xyz(mol)

    try:
        ff = AllChem.MMFFGetMoleculeForceField(mol, mmffVariant="MMFF94s")
        if ff is not None:
            ff.Minimize(maxIts=500)
        else:
            AllChem.UFFOptimizeMolecule(mol)
    except Exception:
        pass

    conf = mol.GetConformer()
    n_atoms = mol.GetNumAtoms()
    lines = [str(n_atoms), ""]
    for i in range(n_atoms):
        atom = mol.GetAtomWithIdx(i)
        symb = atom.GetSymbol()
        pos = conf.GetAtomPosition(i)
        lines.append(f"{symb} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}")
    return "\n".join(lines)


def evaluate_li_solvation_cluster(
    mol: Chem.Mol,
    n_solvents: int = 4,
    solvent_name: str = "ether",
) -> dict[str, float]:
    """Evaluate Li+ solvation binding energy using xTB quantum chemistry.

    Constructs a 3D coordination complex [Li(solvent)_n]+ and computes
    the quantum binding energy:
        ΔE_bind = E([Li(S)_n]+) - (E(Li+) + n * E(S))

    Args:
        mol: RDKit molecule (solvent/electrolyte candidate).
        n_solvents: Number of solvent molecules in the coordination shell (default 4).
        solvent_name: Implicit solvation model for xTB (default "ether").

    Returns:
        Dict with keys:
            - li_binding_energy_kcal: Binding energy in kcal/mol (negative = stable)
            - cluster_homo_eV: HOMO of the cluster
            - cluster_lumo_eV: LUMO of the cluster
    """
    if not _HAS_XTB:
        return {"li_binding_energy_kcal": 0.0, "cluster_homo_eV": 0.0, "cluster_lumo_eV": 0.0}

    xyz_complex = _build_li_solvation_xyz(mol, n_solvents=n_solvents)
    xyz_li = _build_li_plus_xyz()
    xyz_solvent = _build_solvent_xyz(mol)

    result_complex = _run_xtb(xyz_complex, solvent=solvent_name)
    result_li = _run_xtb(xyz_li, solvent=solvent_name)
    result_solvent = _run_xtb(xyz_solvent, solvent=solvent_name)

    if result_complex is None or result_li is None or result_solvent is None:
        return {"li_binding_energy_kcal": 0.0, "cluster_homo_eV": 0.0, "cluster_lumo_eV": 0.0}

    e_complex = result_complex.get("homo_eV", 0.0) + result_complex.get("lumo_eV", 0.0)
    e_li = result_li.get("homo_eV", 0.0) + result_li.get("lumo_eV", 0.0)
    e_solvent = result_solvent.get("homo_eV", 0.0) + result_solvent.get("lumo_eV", 0.0)

    # Convert eV/atom to kcal/mol (1 eV ≈ 23.06 kcal/mol)
    # The binding energy is the energy of the complex minus the sum of fragments
    # We use the HOMO+LUMO sum as a proxy for total electronic energy
    binding_energy_ev = e_complex - (e_li + n_solvents * e_solvent)
    binding_energy_kcal = binding_energy_ev * 23.06

    return {
        "li_binding_energy_kcal": round(binding_energy_kcal, 4),
        "cluster_homo_eV": result_complex.get("homo_eV", 0.0),
        "cluster_lumo_eV": result_complex.get("lumo_eV", 0.0),
    }


# ---------------------------------------------------------------------------
# QuantumBackend — Abstract base for quantum chemistry backends
# ---------------------------------------------------------------------------


class QuantumBackend(ABC):
    """Abstract quantum chemistry backend.

    Implementations must provide an ``evaluate(mol)`` method that returns a
    dict with at minimum ``homo_eV``, ``lumo_eV``, ``dipole_D``, and
    ``quantum_confidence``.
    """

    @abstractmethod
    def evaluate(self, mol: Chem.Mol) -> dict[str, float]:
        ...

    @property
    @abstractmethod
    def method(self) -> str:
        ...

    @property
    @abstractmethod
    def n_calls(self) -> int:
        ...

    def clear_cache(self) -> None:
        """Clear any internal caches. Default no-op."""
        return

    def get_cache_size(self) -> int:
        """Number of cached entries. Default 0."""
        return 0


class XTBBackend(QuantumBackend):
    """xTB (GFN2-xTB) quantum chemistry backend.

    Evaluates frontier orbitals by running the xTB binary on an embedded 3D
    conformer. Uses Boltzmann-weighted multi-conformer averaging for robust
    predictions.

    Args:
        n_conformers: Number of conformers to generate (default 5).
        n_top_conformers: Number of top conformers for Boltzmann averaging (default 3).
        max_workers: Maximum parallel xTB processes (default 4).
        batcher: Optional shared ``BatchXTBRunner`` for batched execution.
        allow_fallback: If True, fall back to TOM when xTB is unavailable.
        solvent: Implicit solvation model (e.g. "ether"). When set,
            appends ``--alpb <solvent>`` to all xTB command lines.
    """

    def __init__(
        self,
        n_conformers: int = _N_CONFORMERS,
        n_top_conformers: int = _N_TOP_CONFORMERS,
        max_workers: int = 4,
        batcher: BatchXTBRunner | None = None,
        allow_fallback: bool = False,
        solvent: str | None = "ether",
    ) -> None:
        if not _HAS_XTB:
            raise EnvironmentError(
                "XTBBackend requires the xtb binary on PATH. "
                "Install via: brew install xtb or https://github.com/grimme-lab/xtb/releases. "
                "In Docker, xtb is installed as part of the build image."
            )
        self._n_conformers = n_conformers
        self._n_top_conformers = n_top_conformers
        self._max_workers = max_workers
        self._batcher = batcher
        self._cache: dict[str, dict[str, float]] = {}
        self._allow_fallback = allow_fallback
        self._n_calls = 0
        self._solvent = solvent

    @property
    def method(self) -> str:
        return "xTB (GFN2-xTB)"

    @property
    def n_calls(self) -> int:
        return self._n_calls

    def clear_cache(self) -> None:
        self._cache.clear()

    def get_cache_size(self) -> int:
        return len(self._cache)

    def _run_xtb_flat(
        self,
        conformers: list[tuple[str, float]],
        n_top: int,
    ) -> tuple[list[dict[str, float]], list[float]]:
        top = conformers[:n_top]
        results: list[dict[str, float]] = []
        energies: list[float] = []
        if self._batcher is not None:
            futures = [self._batcher.submit(xyz) for xyz, _ in top]
            for (xyz, uff_energy), future in zip(top, futures, strict=False):
                xtb_result = future.result()
                if xtb_result is not None:
                    results.append(xtb_result)
                    energies.append(uff_energy)
        else:
            for xyz, uff_energy in top:
                xtb_result = _run_xtb(xyz, solvent=self._solvent)
                if xtb_result is not None:
                    results.append(xtb_result)
                    energies.append(uff_energy)
        return results, energies

    @staticmethod
    def _boltzmann_average(xtb_results: list[dict[str, float]], energies: list[float]) -> dict[str, float]:
        import numpy as np
        weights = _boltzmann_weights(energies)
        homo_w = sum(w * r["homo_eV"] for w, r in zip(weights, xtb_results, strict=False))
        lumo_w = sum(w * r["lumo_eV"] for w, r in zip(weights, xtb_results, strict=False))
        dipole_w = sum(w * r.get("dipole_D", 0.0) for w, r in zip(weights, xtb_results, strict=False))
        homo_vals = [r["homo_eV"] for r in xtb_results]
        conformer_variance = float(np.std(homo_vals, ddof=1)) if len(homo_vals) > 1 else 0.0
        conf = "xtb_high" if conformer_variance < 0.15 else "xtb"
        return {
            "homo_eV": homo_w,
            "lumo_eV": lumo_w,
            "dipole_D": dipole_w,
            "conformer_variance": round(conformer_variance, 4),
            "quantum_confidence": conf,
            "confidence_score": 1.0,
        }

    def _evaluate_with_boltzmann(self, mol: Chem.Mol) -> dict[str, float]:
        conformers = _generate_multi_xyz(mol, n_conformers=self._n_conformers)
        if not conformers:
            result = _run_xtb(_generate_xyz(mol), solvent=self._solvent)
            if result is not None:
                self._n_calls += 1
                result["quantum_confidence"] = "xtb"
                result["confidence_score"] = 1.0
                return result
            msg = "xTB evaluation failed — no conformers could be generated or evaluated."
            raise EnvironmentError(msg)

        xtb_results, energies = self._run_xtb_flat(conformers, self._n_top_conformers)

        if not xtb_results:
            self._n_calls += 1
            result = _run_xtb(conformers[0][0], solvent=self._solvent)
            if result is not None:
                self._n_calls += 1
                result["quantum_confidence"] = "xtb"
                result["confidence_score"] = 1.0
                return result
            msg = "xTB evaluation failed — all conformer calculations returned no result."
            raise EnvironmentError(msg)

        self._n_calls += len(xtb_results)

        if len(xtb_results) == 1:
            result = dict(xtb_results[0])
            result["quantum_confidence"] = "xtb"
            result["confidence_score"] = 1.0
            return result

        return self._boltzmann_average(xtb_results, energies)

    def evaluate(self, mol: Chem.Mol) -> dict[str, float]:
        smiles = Chem.MolToSmiles(mol)
        if smiles in self._cache:
            return dict(self._cache[smiles])

        result = self._evaluate_with_boltzmann(mol)

        if result is not None and "quantum_confidence" in result:
            self._cache[smiles] = result
            return dict(result)

        msg = "xTB evaluation returned no result."
        raise EnvironmentError(msg)


class TOMBackend(QuantumBackend):
    """Topological Orbital Model (TOM) fallback backend.

    Uses the particle-in-a-box model for pi-electrons with heteroatom
    perturbations and a calibration-set Tanimoto confidence score.

    Parameters
    ----------
    calibration_fps : list[ExplicitBitVect] | None
        Pre-loaded calibration fingerprints.  If ``None`` the backend
        will attempt to load them from disk on first evaluation.
    calibration_smiles : list[str] | None
        Corresponding SMILES strings (same length as *calibration_fps*).
    calibration_path : str | None
        Path to ``orbital_calibration.json``.  Only used if
        *calibration_fps* is ``None``.
    """

    def __init__(
        self,
        calibration_fps: list[Chem.DataStructs.ExplicitBitVect] | None = None,
        calibration_smiles: list[str] | None = None,
        calibration_path: str | None = None,
        allow_fallback: bool = False,
    ) -> None:
        self._cache: dict[str, dict[str, float]] = {}
        self._allow_fallback = allow_fallback
        self._n_calls = 0
        self._calibration_fps: list[Chem.DataStructs.ExplicitBitVect] | None = calibration_fps
        self._calibration_smiles: list[str] | None = calibration_smiles
        self._calibration_path: str | None = calibration_path

    @property
    def method(self) -> str:
        return "TOM (Topological Orbital Model)"

    @property
    def n_calls(self) -> int:
        return self._n_calls

    def clear_cache(self) -> None:
        self._cache.clear()

    def get_cache_size(self) -> int:
        return len(self._cache)

    def _ensure_calibration_loaded(self) -> None:
        """Lazy-load calibration fingerprints if not already set."""
        if self._calibration_fps is not None:
            return
        fps, smiles = load_calibration_fingerprints(self._calibration_path)
        self._calibration_fps = fps
        self._calibration_smiles = smiles

    def _compute_max_tanimoto_to_calibration(self, mol: Chem.Mol) -> float:
        """Compute max Tanimoto similarity of *mol* to the calibration set."""
        self._ensure_calibration_loaded()
        if not self._calibration_fps:
            return 0.0
        fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius=2, nBits=2048)
        sims = BulkTanimotoSimilarity(fp, self._calibration_fps)
        return float(max(sims))

    def evaluate(self, mol: Chem.Mol) -> dict[str, float]:
        smiles = Chem.MolToSmiles(mol)
        if smiles in self._cache:
            return dict(self._cache[smiles])

        self._n_calls += 1
        homo, lumo = predict_tom_orbitals(mol)
        L = _longest_conjugation_path(mol)
        n_rings = mol.GetRingInfo().NumRings()

        max_sim = self._compute_max_tanimoto_to_calibration(mol)
        if max_sim < 0.5:
            quantum_conf = "tom_low"
        elif L <= 8 and n_rings <= 2:
            quantum_conf = "tom_high"
        else:
            quantum_conf = "tom_low"

        result: dict[str, float] = {
            "homo_eV": homo,
            "lumo_eV": lumo,
            "dipole_D": 0.0,
            "conformer_variance": 0.0,
            "quantum_confidence": quantum_conf,
            "confidence_score": round(max_sim, 4),
        }
        self._cache[smiles] = result
        return dict(result)


def _resolve_backend(
    backend: QuantumBackend | None = None,
    use_xtb: bool = True,
    n_conformers: int = _N_CONFORMERS,
    n_top_conformers: int = _N_TOP_CONFORMERS,
    max_workers: int = 4,
    batcher: BatchXTBRunner | None = None,
    solvent: str | None = "ether",
) -> QuantumBackend:
    """Resolve a quantum backend from parameters.

    Args:
        backend: Explicit backend instance (takes precedence).
        use_xtb: Whether to attempt using xTB.
        n_conformers: Number of conformers to generate.
        n_top_conformers: Number of top conformers for averaging.
        max_workers: Max workers for xTB batch.
        batcher: Optional shared ``BatchXTBRunner`` for batched execution.
        solvent: Implicit solvation model (e.g. "ether").

    Returns:
        A ``QuantumBackend`` instance.
    """
    if backend is not None:
        return backend
    if use_xtb and _HAS_XTB:
        return XTBBackend(
            n_conformers=n_conformers,
            n_top_conformers=n_top_conformers,
            max_workers=max_workers,
            batcher=batcher,
            solvent=solvent,
        )
    return TOMBackend()


# ---------------------------------------------------------------------------
# QuantumOracle — Unified interface for xTB + TOM fallback
# ---------------------------------------------------------------------------


class QuantumOracle:
    """Quantum-chemical oracle for frontier orbital energies.

    Two-tier evaluation:
       1. xTB (GFN2-xTB) via subprocess — preferred, real QM
       2. Topological Orbital Model (TOM) — conjugation-aware fallback

    Uses a pluggable ``QuantumBackend``. If no backend is supplied, defaults
    to ``XTBBackend`` (if xTB binary is on PATH) or ``TOMBackend``.

    Results are cached by SMILES to avoid redundant computation.

    Args:
        backend: Explicit backend instance (takes precedence).
        use_xtb: Whether to attempt using xTB.
        n_conformers: Number of conformers to generate (default 5).
        n_top_conformers: Number of top conformers for Boltzmann averaging (default 3).
        max_workers: Maximum parallel xTB processes (default 4).
        batch_size: Batch size for xTB batcher (default 10).
        allow_fallback: If True, fall back to TOM when xTB is unavailable.
        flush_interval: Maximum seconds to wait before flushing batcher (default 5.0).
        solvent: Implicit solvation model (e.g. "ether"). When set,
            appends ``--alpb <solvent>`` to all xTB command lines.
    """

    def __init__(
        self,
        backend: QuantumBackend | None = None,
        use_xtb: bool = True,
        n_conformers: int = _N_CONFORMERS,
        n_top_conformers: int = _N_TOP_CONFORMERS,
        max_workers: int = 4,
        batch_size: int = 10,
        allow_fallback: bool = False,
        flush_interval: float = 5.0,
        solvent: str | None = "ether",
    ) -> None:
        self._batcher: BatchXTBRunner | None = None
        if use_xtb and _HAS_XTB:
            self._batcher = BatchXTBRunner(
                batch_size=batch_size,
                flush_interval=flush_interval,
                max_workers=max_workers,
                solvent=solvent,
            )
        self._backend = _resolve_backend(
            backend=backend,
            use_xtb=use_xtb,
            n_conformers=n_conformers,
            n_top_conformers=n_top_conformers,
            max_workers=max_workers,
            batcher=self._batcher,
            solvent=solvent,
        )
        self._cache: dict[str, dict[str, float]] = {}
        self._allow_fallback = allow_fallback

        if isinstance(self._backend, TOMBackend):
            logger.info("QuantumOracle: xTB binary not found — using TOM fallback.")
        else:
            logger.info("QuantumOracle: xTB backend ENABLED.")

    @property
    def method(self) -> str:
        return self._backend.method

    @property
    def n_quantum_calls(self) -> int:
        return self._backend.n_calls

    @property
    def backend(self) -> QuantumBackend:
        """Access the underlying backend instance."""
        return self._backend

    def evaluate(self, mol: Chem.Mol) -> dict[str, float]:
        smiles = Chem.MolToSmiles(mol)
        if smiles in self._cache:
            return dict(self._cache[smiles])

        result = self._backend.evaluate(mol)

        if isinstance(self._backend, XTBBackend):
            li_result = evaluate_li_solvation_cluster(mol)
            result["li_binding_energy_kcal"] = li_result.get("li_binding_energy_kcal", 0.0)
            result["cluster_homo_eV"] = li_result.get("cluster_homo_eV", 0.0)
            result["cluster_lumo_eV"] = li_result.get("cluster_lumo_eV", 0.0)

        self._cache[smiles] = result
        return dict(result)

    def clear_cache(self) -> None:
        self._cache.clear()
        self._backend.clear_cache()

    def get_cache_size(self) -> int:
        return len(self._cache)

    def flush_batcher(self) -> None:
        """Force-flush any pending xTB jobs in the batcher."""
        if self._batcher is not None:
            self._batcher.flush()

    @property
    def batcher_pending(self) -> int:
        """Number of xTB jobs still pending in the batcher queue."""
        return self._batcher.pending_count if self._batcher is not None else 0
