#!/usr/bin/env python3
"""Auto-generate docs/MODEL_CARD.md from live benchmarks and pyproject.toml.

Usage:
    python scripts/generate_model_card.py

The model card documents intended use, known limitations (including
explicit mention of TOM failure for cross-conjugated systems),
performance metrics from live benchmarks, and dependencies. It is
regenerated whenever benchmarks are updated via update_benchmark_docs.py
to ensure it never goes stale.
"""

from __future__ import annotations

import tomllib
from pathlib import Path
from typing import Any

_PROJECT_ROOT = Path(__file__).resolve().parent.parent


def _load_benchmarks_md() -> str:
    """Read the auto-generated docs/benchmarks.md."""
    path = _PROJECT_ROOT / "docs" / "benchmarks.md"
    if not path.exists():
        return (
            "*Benchmarks not yet generated — run"
            " `python scripts/update_benchmark_docs.py` first.*\n"
        )
    with open(path) as f:
        return f.read()


def _load_pyproject() -> dict[str, Any]:
    """Parse pyproject.toml for dependencies and metadata."""
    path = _PROJECT_ROOT / "pyproject.toml"
    with open(path, "rb") as f:
        return tomllib.load(f)


def _format_deps(deps: list[str]) -> str:
    """Format a list of dependency specifiers as markdown bullet points."""
    return "\n".join(f"- `{d}`" for d in deps)


def main() -> None:
    docs_dir = _PROJECT_ROOT / "docs"
    docs_dir.mkdir(exist_ok=True)

    benchmarks_md = _load_benchmarks_md()
    pyproject = _load_pyproject()

    project_info = pyproject.get("project", {})
    version: str = project_info.get("version", "unknown")
    description: str = project_info.get("description", "")

    deps: list[str] = project_info.get("dependencies", [])
    deps_str = _format_deps(deps)

    opt_deps = project_info.get("optional-dependencies", {})
    opt_deps_str = ""
    for group, group_deps in opt_deps.items():
        if group_deps:
            opt_deps_str += f"\n### `[{group}]`\n\n{_format_deps(group_deps)}\n"

    model_card = f"""# Model Card: Aurelius Discovery Engine v{version}

*Do not edit manually. Auto-generated by `scripts/generate_model_card.py`.*

---

## Intended Use

The Aurelius Discovery Engine is an open-source evolutionary algorithm platform
for **battery electrolyte discovery**.

{description}

It combines:

- **Group-Contribution (GC) fragment-additivity** — dielectric, viscosity,
  Li+ solvation, and cohesive energy density proxies using SMARTS-based
  functional group counting with Michaelis-Menten saturation and non-linear
  cross-terms. Physical basis: bulk thermodynamic properties are approximately
  linear in polar group density for moderate-MW molecules.
- **Topological Orbital Model (TOM)** — closed-form HOMO/LUMO prediction using
  Wiener compactness and heteroatom perturbation theory, calibrated to DFT
  reference data. No quantum chemistry calculation required.
- **xTB (GFN2-xTB)** — optional higher-accuracy quantum chemistry backend for
  frontier orbital energies (requires external xTB binary).
- **Random Forest UQ Ensemble** — 5-model ensemble (n_estimators=50, max_depth=5)
  for uncertainty quantification on GC predictions, trained on the external
  property benchmark. High variance flags out-of-distribution molecules.

The platform screens candidate electrolyte solvents generated via evolutionary
algorithms (EA) for thermodynamic and transport properties relevant to Li-ion,
Li-metal, and Na-ion batteries.

---

## Limitations

### Topological Orbital Model (TOM)
- **TOM fails for cross-conjugated systems** because the topological orbital
  model assumes a single dominant conjugation pathway. Cross-conjugated molecules
  (e.g., benzophenone, quinones, dendralenes, benzodithiophene-4,8-dione) have
  spatially separated π-systems that do not contribute coherently to the
  frontier orbital energies via the longest-path algorithm, leading to
  unreliable HOMO/LUMO predictions. Users should enable xTB for such molecules.
- TOM does **not** model excited states, charge-transfer states, triplet
  energies, or spin-orbit coupling.
- TOM parameters are calibrated against DFT (B3LYP/6-31G*) for CHONF molecules.
  Heavier elements (Si, P, S beyond sulfone) have limited calibration data.

### Group-Contribution Model
- The GC model predicts bulk property *proxies* (unitless), not physical
  property values. The dielectric proxy, for example, correlates with
  experimental dielectric constant (Spearman ρ > 0.6) but is not directly
  comparable in magnitude.
- GC predictions are unreliable for molecules with:
  - Molecular weight > 500 Da (linear accumulation overestimates real values)
  - > 20 rotatable bonds (conformational entropy not captured by fragment additivity)
  - Extreme fluorination (≥6 F atoms) without polar solvation sites (<2 polar atoms)
- Cross-term corrections are limited to pairwise carbonate/ether/sulfone/nitrile
  combinations documented in gc.py. Higher-order (ternary+ group) interactions
  are not modelled.

### Validation Coverage
- External benchmark: ~75 molecules covering carbonates, ethers, sulfones,
  nitriles, phosphates, esters, amides, and sulfoxides.
- **Known gaps:** silicon-containing solvents, ionic liquids, highly branched
  polyethers, crown ethers, borate/boronate compounds, and sulfonamides.
  See `docs/examples/benchmark_gap_analysis.json` for detailed gap analysis.

---

## Performance Metrics

{benchmarks_md}

---

## Dependencies

{deps_str}{opt_deps_str}

---

*Generated by Aurelius Engine v{version}*
"""
    output_path = docs_dir / "MODEL_CARD.md"
    with open(output_path, "w") as f:
        f.write(model_card)

    print(f"Model card written to {output_path}")


if __name__ == "__main__":
    main()
