"""Hybrid quantum/GC property oracle for Project Aurelius.

Provides:
  - PropertyOracle: Multi-objective oracle (HOMO, LUMO, Dielectric, Viscosity, Li+ Solvation)
  - QuantumOracle: Two-tier quantum backend (xTB / TOM fallback)
  - GC model functions for bulk property prediction
"""

from __future__ import annotations

from aurelius.scoring.oracle.gc import (
    _CROSS_TERMS,
    _GC_BASE_DIELECTRIC,
    _GC_BASE_LI_SOLVATION,
    _GC_BASE_VISCOSITY,
    _GC_FRAGMENTS,
    _GC_SATURATION_K,
    _compute_dielectric_cross_terms,
    _count_branch_points,
    _count_fragments,
    _count_stereocenters,
    _saturate_contrib,
    compute_gc_domain_penalty,
    get_data_source,
    mixture_synergy_bonus,
    mixture_synergy_bonus_n,
    predict_dielectric_proxy,
    predict_ionic_conductivity_proxy,
    predict_li_solvation_proxy,
    predict_mixture_dielectric,
    predict_mixture_dielectric_n,
    predict_mixture_li_solvation,
    predict_mixture_li_solvation_n,
    predict_mixture_viscosity,
    predict_mixture_viscosity_n,
    predict_viscosity_proxy,
)
from aurelius.scoring.oracle.oracle import PropertyOracle
from aurelius.scoring.oracle.quantum import (
    _ATOM_PERTURBATIONS,
    _HAS_XTB,
    _XTB_HOMO_RE,
    _XTB_LUMO_RE,
    QuantumOracle,
    _count_aromatic_rings,
    _count_heteroatom_perturbations,
    _find_xtb_binary,
    _generate_xyz,
    _generate_xyz_geometry_optimized,
    _is_conjugated_bond,
    _longest_conjugation_path,
    _parse_xtb_output,
    _run_xtb,
    _wiener_index,
    compute_quantum_domain_penalty,
    has_xtb,
    predict_tom_orbitals,
)
from aurelius.scoring.oracle.dft_validator import (
    DFT_GEOMETRY_OPT_THRESHOLD,
    DFTValidator,
    dft_geometry_optimize,
    has_orca,
    spearman_correlation,
    _build_orca_input,
    _parse_orca_output,
)

__all__ = [
    "PropertyOracle",
    "QuantumOracle",
    "compute_gc_domain_penalty",
    "compute_quantum_domain_penalty",
    "get_data_source",
    "has_xtb",
    "predict_dielectric_proxy",
    "predict_viscosity_proxy",
    "predict_li_solvation_proxy",
    "predict_ionic_conductivity_proxy",
    "predict_tom_orbitals",
    "predict_mixture_dielectric",
    "predict_mixture_viscosity",
    "predict_mixture_li_solvation",
    "mixture_synergy_bonus",
    "predict_mixture_dielectric_n",
    "predict_mixture_viscosity_n",
    "predict_mixture_li_solvation_n",
    "mixture_synergy_bonus_n",
    "_GC_FRAGMENTS",
    "_count_fragments",
    "_count_branch_points",
    "_count_stereocenters",
    "_compute_dielectric_cross_terms",
    "_CROSS_TERMS",
    "_GC_BASE_DIELECTRIC",
    "_GC_BASE_LI_SOLVATION",
    "_GC_BASE_VISCOSITY",
    "_GC_SATURATION_K",
    "_saturate_contrib",
    "_HAS_XTB",
    "_find_xtb_binary",
    "_generate_xyz",
    "_generate_xyz_geometry_optimized",
    "_run_xtb",
    "_parse_xtb_output",
    "_XTB_HOMO_RE",
    "_XTB_LUMO_RE",
    "_longest_conjugation_path",
    "_is_conjugated_bond",
    "_ATOM_PERTURBATIONS",
    "_count_heteroatom_perturbations",
    "_count_aromatic_rings",
    "_wiener_index",
    "DFTValidator",
    "DFT_GEOMETRY_OPT_THRESHOLD",
    "dft_geometry_optimize",
    "has_orca",
    "spearman_correlation",
    "_build_orca_input",
    "_parse_orca_output",
]
