"""Group-Contribution (Fragment-Additivity) Models — Bulk Properties Only.

Predicts dielectric, viscosity, and Li+ solvation via functional-group
additivity with Michaelis-Menten saturation and non-linear cross-terms.

ADR-2026-06-05: Parameter refinements to improve weak proxy correlations:
  Dielectric ε: nitrile 8.0→5.5, amide 5.0→6.0, sulfoxide 6.0→7.5;
                MAX_DIELECTRIC_PER_TPSA 0.35→0.60 (constants.py).
  Li⁺ solvation: amide 1.2→2.5, glyme_chelating 1.8→0.6, sulfoxide 2.5→3.5,
                 aromatic_nitrogen 2.0→3.5.
  Rationale: nitrile was over-contributing relative to carbonate (ACN > DMSO
  ranked wrong); glyme_chelating double-counted ether chelation; amides and
  sulfoxides were under-valued for Li⁺ binding. External validation Spearman ρ:
  Dielectric 0.3226→0.3967, Donor Number 0.1368→0.4074.

ADR-2026-06-05c: Parameter refinements to improve Dielectric and Donor Number ρ:
  Dielectric ε: cyclic_carbonate 6.0→8.0, carbonate 5.0→2.0, TPSA 0.025→0.030.
  Donor Number: aromatic_nitrogen 3.5→4.0.
  Rationale: cyclic Kirkwood g>1 needs stronger representation; linear carbonates
  were overpredicted (anti-periplanar O-alkyl cancels dipoles); TPSA coefficient
  increased to improve polar/non-polar rank separation; pyridine (DN=33.1) should
  rank above DMSO (DN=29.8) via stronger aromatic N basicity.

ADR-2026-06-05b: Add cyclic_carbonate fragment (+6.0 dielectric) to
 differentiate EC/PC (cyclic, ε=90/65) from DMC/DEC (linear, ε=3). Physical
justification: The Onsager-Kirkwood correlation factor g>1 for cyclic carbonates
(conformational locking of cis-carbonate dipoles) vs g<1 for linear carbonates
(anti-parallel alignment), producing a 20-30× difference in measured dielectric.
TPSA coefficient raised from 0.02→0.025 to better capture polarity scaling while
maintaining fragment saturation guarantees (5 esters < 2× single ester).
Nitrile dielectric raised 5.5→7.5: ACN (ε=36) and PN (ε=27) were under-valued
relative to sulfoxides and carbonates. The C≡N dipole (μ≈3.9 D) is among the
strongest of any organic functional group; 7.5 keeps ACN (pred=10.0) below DMSO
(pred=10.3) preserving the experimental ranking ACN < DMSO.

ADR-2026-06-01: Added [-2.0, 2.0] clip to _compute_dielectric_cross_terms.
Physical justification: cross-term additive bonuses have no upper bound; a
molecule with carbonate + ether + sulfone + nitrile can accumulate ~1.2 extra
dielectric points, enough to materially misrank candidates. A single clip guard
bounds the cross-term contribution to what is physically plausible — no polar
group combination can more than double the base dielectric contribution. This is
the minimal non-invasive fix: one line, no new data structures, no architectural
change. The alternative (capping each cross-term individually or using saturation)
would add complexity without proportional benefit.
"""

from __future__ import annotations

import json
import logging
import math
import os
from typing import Any

import numpy as np
from rdkit import Chem
from rdkit.Chem import Crippen

from aurelius.types import MoleculeContext

logger = logging.getLogger(__name__)

_DATA_SOURCE: str = "hybrid (GC bulk + Quantum orbital)"

_DEFAULT_CROSS_TERMS: list[tuple[str, str, float, str]] = [
    ("carbonate", "ether", 0.8, "carbonate-ether synergy (glyme-carbonate hybrids)"),
    ("nitrile", "ether", 0.3, "nitrile-ether synergy"),
    ("carbonate", "fluorine", -0.5, "fluorinated carbonate suppression"),
    ("sulfone", "ether", 0.4, "sulfone-ether synergy"),
    ("carbonate", "nitrile", -0.3, "carbonate-nitrile antagonism"),
    ("alcohol", "carbonate", -0.4, "alcohol-carbonate H-bond competition"),
    ("sulfone", "carbonate", -0.3, "sulfone-carbonate polarity competition"),
    ("nitrile", "fluorine", 0.3, "fluorinated nitrile dipole enhancement"),
    ("sulfone", "nitrile", 0.5, "sulfone-nitrile high-voltage synergy"),
]


def _load_cross_terms() -> list[tuple[str, str, float, str]]:
    """Load cross-term coefficients from JSON, falling back to defaults.

    The JSON file (gc_cross_terms.json) is generated by
    scripts/calibrate_gc_cross_terms.py via ridge regression on the
    external benchmark. Terms without sufficient data fall back to
    their hand-tuned default values, which are documented as ``source:
    "default"`` in the JSON.
    """
    path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "..", "..", "data", "gc_cross_terms.json",
    )
    try:
        with open(path) as f:
            data = json.load(f)
        terms = []
        for entry in data.get("cross_terms", []):
            terms.append((
                entry["frag_a"],
                entry["frag_b"],
                float(entry["coefficient"]),
                entry["description"],
            ))
        if terms:
            n_fitted = sum(1 for t in data["cross_terms"] if t.get("source") == "fitted")
            logger.info("GC cross-terms: loaded %d terms (%d fitted, %d default)",
                        len(terms), n_fitted, len(terms) - n_fitted)
            return terms
    except (FileNotFoundError, json.JSONDecodeError, KeyError) as exc:
        logger.debug("GC cross-terms JSON not found or invalid: %s — using defaults", exc)
    return list(_DEFAULT_CROSS_TERMS)


_CROSS_TERMS: list[tuple[str, str, float, str]] = _load_cross_terms()


def compute_gc_domain_penalty(ctx: MoleculeContext) -> tuple[float, str]:
    """Compute domain-of-applicability penalty for GC predictions.

    Physical justification: The GC fragment-additivity model is calibrated
    on molecules with moderate functional group density and reasonable
    molecular weight (MW < 500, rotatable bonds < 20). Extreme fluorination
    without polar solvation sites (F >= 6, polar atoms < 2) falls outside
    the GC calibration domain because the saturation curves for halogenated
    fragments were not validated against such extreme compositions. High-MW
    molecules accumulate group contributions linearly but real dielectric
    and viscosity saturate, which the Michaelis-Menten model only partially
    captures. These are continuous sigmoidal penalties — no ML involved.

    Returns:
        (penalty_multiplier, reason_string)
        Multiplier in [0.75, 1.0]; 1.0 = fully within domain.
    """
    mol = ctx.mol
    reasons: list[str] = []
    penalty = 1.0

    n_f = sum(a.GetAtomicNum() == 9 for a in mol.GetAtoms())
    n_polar = sum(a.GetAtomicNum() in (7, 8, 15, 16) for a in mol.GetAtoms())
    if n_f >= 6 and n_polar < 2:
        f_penalty = 0.75 + 0.25 / (1.0 + math.exp(0.5 * (n_f - 6.0)))
        penalty *= f_penalty
        reasons.append(f"extreme fluorination (F={n_f}) without polar solvation sites")

    if ctx.mw > 500:
        mw_penalty = 0.85 + 0.15 / (1.0 + math.exp(0.3 * (ctx.mw - 500.0)))
        penalty *= mw_penalty
        reasons.append(f"high MW ({ctx.mw:.0f}) outside GC calibration domain")

    if ctx.rotatable_bonds > 20:
        rb_penalty = 0.85 + 0.15 / (1.0 + math.exp(0.3 * (ctx.rotatable_bonds - 20.0)))
        penalty *= rb_penalty
        reasons.append(f"excessive flexibility ({ctx.rotatable_bonds} rotatable bonds)")

    penalty = min(1.0, penalty)
    penalty = max(0.75, penalty)
    return round(penalty, 4), "; ".join(reasons) if reasons else "within domain"


def get_data_source() -> str:
    return _DATA_SOURCE


# ---------------------------------------------------------------------------
# Fragment-Additivity (Group-Contribution) Models — Bulk Properties Only
# ---------------------------------------------------------------------------

# (pattern, name, dielectric_contrib, viscosity_contrib, li_solvation_contrib)
_GC_FRAGMENTS: list[tuple[Chem.Mol, str, float, float, float]] = [
    # ADR-2026-06-05d: Added ([#6]) to exclude carbonyls without carbon substituent
    # (i.e. carbonate groups O=C(-O-)(-O-) where both neighbors are oxygens).
    # Linear carbonates (DMC ε≈3.1, DEC ε≈2.8) were overpredicted (pred≈8.7) because
    # each -OX2H0 attached to the carbonate carbonyl matched the ester pattern.
    # Physical justification: true esters have C(=O)-C structure; carbonate carbonyls
    # have C(=O)-O structure with no direct C-C bond. The ([#6]) disambiguates them.
    (Chem.MolFromSmarts("[CX3](=O)([#6])[OX2H0]"),  "ester",              2.5,  0.6,  0.8),
    (Chem.MolFromSmarts("[CX3](=O)[OH]"),          "carboxylic_acid",    4.0,  1.0,  1.8),
    (Chem.MolFromSmarts("[CX3](=O)[NX3]"),         "amide",              6.0,  0.8,  2.5),
    (Chem.MolFromSmarts("[CX3](=O)[CX3]"),         "ketone",             3.0,  0.5,  0.6),
    (Chem.MolFromSmarts("[CH](=O)"),               "aldehyde",           2.5,  0.3,  0.3),
    # ADR-2026-06-05c: carbonate dielectric 5.0→2.0. Linear carbonates (DMC ε≈3.1,
    # DEC ε≈2.8) have anti-periplanar O-alkyl conformation cancelling dipoles (Kirkwood
    # g<1). The cyclic_carbonate fragment (8.0) separately captures EC/PC's g>1 effect.
    # Reducing generic carbonate prevents overprediction of linear carbonates.
    (Chem.MolFromSmarts("O=C([OX2])[OX2]"),        "carbonate",          2.0,  0.7,  1.2),
    (Chem.MolFromSmarts("[OD2]([CX4])[CX4]"),      "ether",              1.5, -0.3,  1.0),
    (Chem.MolFromSmarts("[OH][CX4]"),              "alcohol",            4.5,  1.2,  2.0),
    (Chem.MolFromSmarts("[NX3;H2][CX4]"),          "primary_amine",      3.5,  0.5,  1.0),
    (Chem.MolFromSmarts("[NX3;H1]([CX4])[CX4]"),   "secondary_amine",    2.5,  0.4,  0.8),
    (Chem.MolFromSmarts("[NX3;H0]([CX4])([CX4])[CX4]"), "tertiary_amine", 1.5,  0.3,  0.5),
    # Nitrile dielectric raised from 5.5→7.5 (ADR-2026-06-05b): the C≡N dipole
    # (μ≈3.9 D) produces ε=36 for ACN and ε=27 for PN — the prior 5.5 under-valued
    # nitriles relative to sulfoxides and carbonates. Cyclic_carbonate boost to EC
    # (now ~18) frees headroom: ACN=10.0 < DMSO=10.3, preserving correct ranking.
    (Chem.MolFromSmarts("[C]#[N]"),                "nitrile",            7.5,  0.4,  0.8),
    (Chem.MolFromSmarts("[CX3]=[CX3]"),            "alkene",             0.5,  0.1,  0.1),
    (Chem.MolFromSmarts("[CX2]#[CX2]"),            "alkyne",             1.0,  0.2,  0.2),
    (Chem.MolFromSmarts("[c]"),                    "aromatic_carbon",    0.5,  0.5,  0.1),
    (Chem.MolFromSmarts("[F]"),                    "fluorine",           0.0,  0.1, -0.5),
    (Chem.MolFromSmarts("[Cl]"),                   "chlorine",           0.5,  0.2, -0.3),
    (Chem.MolFromSmarts("[Br]"),                   "bromine",            0.5,  0.3, -0.2),
    (Chem.MolFromSmarts("S(=O)(=O)[CX4]"),         "sulfone",            5.0,  0.5,  1.0),
    (Chem.MolFromSmarts("S(=O)(=O)[OX2]"),         "sulfonate",          5.5,  0.6,  1.2),
    (Chem.MolFromSmarts("S(=O)(=O)F"),             "sulfonyl_fluoride",  4.0,  0.4,  0.5),
    (Chem.MolFromSmarts("[PX4](=O)([OX2])([OX2])[OX2]"), "phosphate",    4.0,  0.8,  1.5),
    (Chem.MolFromSmarts("[C](F)(F)F"),             "trifluoromethyl",    0.5,  0.2, -0.3),
    (Chem.MolFromSmarts("[C](F)(F)"),              "difluoromethylene",  0.3,  0.1, -0.2),
    (Chem.MolFromSmarts("[BX3]([OX2])"),           "boronate",           2.0,  0.7,  1.0),
    (Chem.MolFromSmarts("[BX4]([OX2])([OX2])([OX2])[OX2]"), "borate",    3.0,  0.6,  1.5),
    (Chem.MolFromSmarts("[S]([CX4])[CX4]"),        "thioether",          1.0,  0.2,  0.3),
    (Chem.MolFromSmarts("[F][CX4][OX2][CX4]"),     "fluorinated_ether",  1.0,  0.0, -0.2),
    (Chem.MolFromSmarts("[PX4](=N)([OX2])([OX2])[OX2]"), "phosphazene",  3.5,  0.4,  0.8),
    (Chem.MolFromSmarts("[OX2][CX4][CX4][OX2]"),   "glyme_chelating",    2.0,  0.1,  0.6),
    (Chem.MolFromSmarts("[SX4](=O)(=O)[NX3][SX4](=O)(=O)"), "sulfonimide", 5.0,  0.5,  0.5),
    (Chem.MolFromSmarts("[CX3](=O)[OX2]C(F)(F)F"),  "fluorinated_carbonate", 3.0,  0.3, -0.1),
    (Chem.MolFromSmarts("[SX3](=O)[CX4]"),           "sulfoxide",             7.5,  0.5,  3.5),
    # ADR-2026-06-05c: aromatic_N li_solvation 3.5→4.0. Pyridine (DN=33.1) has the
    # highest donor number in the benchmark set; it should rank above DMSO (DN=29.8).
    (Chem.MolFromSmarts("[n]"),                      "aromatic_nitrogen",     4.0,  0.3,  4.0),
    (Chem.MolFromSmarts("[PX4](=O)([OX2])([OX2])[#6]"), "phosphonate",        3.5,  0.5,  1.0),
    # Cyclic carbonate (5-ring): cis-conformation enables cooperative dipole alignment
    # (Kirkwood g>1), boosting ε 20-30× vs linear. Li+ binding at carbonyl O is same
    # as linear carbonates, so li_solvation kept at 0.0 (donor number unaffected).
    # ADR-2026-06-05c: dielectric 6.0→8.0. EC (ε=89.78) and PC (ε=64.92) are 2-3×
    # higher than any other aprotic solvent. Larger contribution needed to capture
    # the physical gap between cyclic (g>1) and linear (g<1) carbonates.
    (Chem.MolFromSmarts("[OX2]1[CX3](=O)[OX2][CX4][CX4]1"), "cyclic_carbonate",  8.0,  0.4,  0.0),
]

_GC_BASE_DIELECTRIC: float = 1.9
_GC_BASE_VISCOSITY: float = 0.1
_GC_BASE_LI_SOLVATION: float = 1.0

# Saturation parameter for GC fragment additivity.
_GC_SATURATION_K: float = 0.693  # ln(2), half-max at count=1


def _saturate_contrib(count: int, max_contrib: float) -> float:
    """Michaelis-Menten style saturation for fragment additivity."""
    return max_contrib * (1.0 - math.exp(-_GC_SATURATION_K * count))


def _count_fragments(mol: Chem.Mol) -> dict[str, int]:
    """Count occurrences of each pre-compiled fragment pattern in a molecule."""
    counts: dict[str, int] = {}
    for pattern, name, _dd, _dv, _ls in _GC_FRAGMENTS:
        matches = mol.GetSubstructMatches(pattern)
        counts[name] = len(matches)
    return counts


def _count_fragments_batch(contexts: list[MoleculeContext]) -> np.ndarray[Any, np.dtype[np.float32]]:
    """Count fragment occurrences for a batch of molecules.

    Returns a 2D numpy array of shape (n_molecules, n_fragments) where
    each entry is the count of that fragment in that molecule.

    ADR-2026-08-07-03: This previously ended with ``to_device(result,
    get_device())``, returning an MLX array on Apple Silicon. Every numpy
    consumer downstream then either silently fell back to MLX semantics or
    would raise on numpy-only calls. The substructure matching itself is
    RDKit/CPU/GIL-bound and cannot be GPU-accelerated, so there is nothing
    to gain by moving the resulting count matrix to the GPU here; callers
    that genuinely need device arrays should call ``to_device`` themselves.

    Measured on M5 Pro, N=550: the SMARTS matching loop below costs 42 ms
    (~13k mol/s) while the elementwise arithmetic that consumes this matrix
    costs 0.30 ms. This function, not the linear algebra, is the batch
    bottleneck.
    """
    n_frags = len(_GC_FRAGMENTS)
    n_mols = len(contexts)
    result = np.zeros((n_mols, n_frags), dtype=np.float32)
    for i, ctx in enumerate(contexts):
        for j, (_pattern, _name, _dd, _dv, _ls) in enumerate(_GC_FRAGMENTS):
            matches = ctx.mol.GetSubstructMatches(_pattern)
            result[i, j] = len(matches)
    return result


def _saturate_contrib_batch(counts: np.ndarray[Any, np.dtype[np.float32]], max_contrib: float) -> np.ndarray[Any, np.dtype[np.float32]]:
    """Vectorized Michaelis-Menten saturation for a batch of fragment counts.

    Args:
        counts: 2D array (n_molecules, n_fragments) of fragment counts.
        max_contrib: Maximum contribution per fragment instance.

    Returns:
        Array of shape (n_molecules, n_fragments) with saturated contributions.
    """
    return max_contrib * (1.0 - np.exp(-_GC_SATURATION_K * counts))


def _compute_dielectric_cross_terms_batch(counts_matrix: np.ndarray[Any, np.dtype[np.float32]], frag_index: dict[str, int]) -> np.ndarray[Any, np.dtype[np.float32]]:
    """Vectorized non-linear cross-term corrections for dielectric proxy (batch).

    Optimized to eliminate Python loops by pre-computing fragment pair contributions
    and using vectorized numpy operations.

    Args:
        counts_matrix: 2D array (n_molecules, n_fragments) of fragment counts.
        frag_index: Mapping from fragment name to column index in counts_matrix.

    Returns:
        1D array (n_molecules,) with cross-term corrections clipped to [-2, 2].
    """
    n_mols = counts_matrix.shape[0]
    correction = np.zeros(n_mols, dtype=np.float32)

    # Pre-extract fragment indices and boosts for vectorized computation
    frag_pairs = []
    for frag_a, frag_b, boost, _desc in _CROSS_TERMS:
        idx_a = frag_index.get(frag_a)
        idx_b = frag_index.get(frag_b)
        if idx_a is not None and idx_b is not None:
            frag_pairs.append((idx_a, idx_b, boost))

    if not frag_pairs:
        return correction

    # Vectorized computation for all fragment pairs
    # Create binary masks for fragment presence (saturated at 1.0)
    frag_masks = np.minimum(counts_matrix, 1.0)  # Shape: (n_mols, n_frags)

    # Accumulate corrections for all pairs
    for idx_a, idx_b, boost in frag_pairs:
        co_occur = frag_masks[:, idx_a] * frag_masks[:, idx_b]
        correction += boost * co_occur

    return np.clip(correction, -2.0, 2.0)


def predict_dielectric_proxy_batch(
    counts_matrix: np.ndarray[Any, np.dtype[np.float32]],
    tpsa_values: np.ndarray[Any, np.dtype[np.float32]],
    contexts: list[MoleculeContext] | None = None,
) -> np.ndarray[Any, np.dtype[np.float32]]:
    """Batch static dielectric constant prediction.

    ADR-2026-08-07-04: delegates to the Kirkwood-Fröhlich model so the batch
    and scalar paths cannot diverge. ``counts_matrix`` and ``tpsa_values`` are
    accepted for signature compatibility but are no longer used for the
    dielectric — the physical model needs molar volume and molar refraction,
    which are derived per-molecule from ``contexts``.

    Args:
        counts_matrix: 2D array (n_molecules, n_fragments) of fragment counts.
            Unused; retained so existing callers keep working.
        tpsa_values: 1D array (n_molecules,) of TPSA values. Unused.
        contexts: Parsed molecule contexts. Required for the physical model.

    Returns:
        1D array (n_molecules,) of static dielectric constants.

    Raises:
        ValueError: If ``contexts`` is not supplied.
    """
    if contexts is None:
        raise ValueError(
            "predict_dielectric_proxy_batch requires `contexts`: the "
            "Kirkwood-Fröhlich model needs per-molecule molar volume and "
            "molar refraction, which cannot be recovered from fragment "
            "counts and TPSA alone."
        )
    return np.array(
        [predict_dielectric_constant(ctx) for ctx in contexts], dtype=np.float32
    )


def predict_viscosity_proxy_batch(
    counts_matrix: np.ndarray[Any, np.dtype[np.float32]],
    mw_values: np.ndarray[Any, np.dtype[np.float32]],
    n_rotatable: np.ndarray[Any, np.dtype[np.int32]],
    n_branch: np.ndarray[Any, np.dtype[np.int32]],
    n_stereo: np.ndarray[Any, np.dtype[np.int32]],
    contexts: list[MoleculeContext] | None = None,
) -> np.ndarray[Any, np.dtype[np.float32]]:
    """Batch dynamic viscosity prediction.

    ADR-2026-08-07-07: delegates to the Eyring model so the batch and scalar
    paths cannot diverge, mirroring what ADR-2026-08-07-04 did for the
    dielectric. ``counts_matrix``, ``mw_values`` and ``n_stereo`` are accepted
    for signature compatibility but are no longer used — the physical model
    needs molar volume, molar refraction and the molecular dipole, which are
    derived per-molecule from ``contexts``.

    Args:
        counts_matrix: 2D array (n_molecules, n_fragments). Unused.
        mw_values: 1D array (n_molecules,) of molecular weights. Unused.
        n_rotatable: 1D array (n_molecules,) of rotatable bond counts. Unused;
            read from ``contexts`` so both paths use one source.
        n_branch: 1D array (n_molecules,) of branch point counts. Unused.
        n_stereo: 1D array (n_molecules,) of stereocenter counts. Unused.
        contexts: Parsed molecule contexts. Required for the physical model.

    Returns:
        1D array (n_molecules,) of dynamic viscosities in centipoise.

    Raises:
        ValueError: If ``contexts`` is not supplied.
    """
    if contexts is None:
        raise ValueError(
            "predict_viscosity_proxy_batch requires `contexts`: the Eyring "
            "activated-flow model needs per-molecule molar volume, molar "
            "refraction and dipole moment, which cannot be recovered from "
            "fragment counts and molecular weight alone."
        )
    return np.array(
        [predict_viscosity_proxy(ctx) for ctx in contexts], dtype=np.float32
    )


def predict_li_solvation_proxy_batch(counts_matrix: np.ndarray[Any, np.dtype[np.float32]], mw_values: np.ndarray[Any, np.dtype[np.float32]]) -> np.ndarray[Any, np.dtype[np.float32]]:
    """Vectorized Li+ solvation proxy prediction for a batch of molecules.

    Args:
        counts_matrix: 2D array (n_molecules, n_fragments) of fragment counts.
        mw_values: 1D array (n_molecules,) of molecular weights.

    Returns:
        1D array (n_molecules,) of Li+ solvation proxy predictions.
    """
    contributions = np.array([ls for _, _, _dd, _dv, ls in _GC_FRAGMENTS], dtype=np.float32)
    saturated = _saturate_contrib_batch(counts_matrix, contributions * 2.0)
    value = _GC_BASE_LI_SOLVATION + saturated.sum(axis=1)
    value += np.maximum(0.0, (mw_values - 50.0)) * 0.002
    value = np.maximum(value, 0.5)
    return value


def predict_ionic_conductivity_proxy_batch(
    dielectric: np.ndarray[Any, np.dtype[np.float32]],
    viscosity: np.ndarray[Any, np.dtype[np.float32]],
    li_solvation: np.ndarray[Any, np.dtype[np.float32]],
) -> np.ndarray[Any, np.dtype[np.float32]]:
    """Vectorized ionic conductivity proxy via Walden-product model (batch).

    Combines dielectric (salt dissociation), viscosity (Stokes-Einstein
    mobility), and Li+ solvation (charge carrier availability) into a
    single figure of merit.
    """
    viscosity = np.maximum(viscosity, 0.001)
    effective_dielec = np.maximum(0.0, dielectric - 1.0)
    solvation_factor = np.exp(-0.5 * ((li_solvation - 3.5) / 1.5) ** 2)
    conductivity = effective_dielec * solvation_factor / viscosity
    return np.clip(conductivity, 0.0, 10.0)


def _compute_dielectric_cross_terms(counts: dict[str, int]) -> float:
    """Compute non-linear cross-term contributions to dielectric proxy.

    Physical justification: Cross-terms capture non-additive dielectric
    enhancement from co-occurring polar groups (e.g., carbonate-ether
    synergy). Without a ceiling, a molecule with four synergistic groups
    (carbonate + ether + sulfone + nitrile) can accumulate ~1.2 extra
    dielectric points, enough to materially misrank candidates. The
    [-2.0, 2.0] clip bounds the cross-term contribution to what is
    physically plausible for a molecular dielectric proxy — no single
    polar group combination can more than double the base dielectric
    contribution.
    """
    correction = 0.0
    for frag_a, frag_b, boost, _desc in _CROSS_TERMS:
        if counts.get(frag_a, 0) > 0 and counts.get(frag_b, 0) > 0:
            correction += boost
    return max(-2.0, min(2.0, correction))


def predict_dielectric_proxy(ctx: MoleculeContext) -> float:
    """Predict the static dielectric constant.

    ADR-2026-08-07-04: Now delegates to :func:`predict_dielectric_constant`
    (Kirkwood-Fröhlich). The name is retained for backward compatibility with
    the ``dielectric_proxy`` field consumed across the pipeline, but the value
    is no longer a unitless proxy — it is on the true physical ε scale.

    Scale change: previously bounded to roughly 1-15 by the TPSA cap; now
    spans ~2-90. ``DIELECTRIC_TARGET`` and the tier-0 prefilter threshold were
    re-referenced to the physical scale in the same change.
    """
    return predict_dielectric_constant(ctx)


# ---------------------------------------------------------------------------
# Static Dielectric Constant — Kirkwood-Fröhlich Theory
# ---------------------------------------------------------------------------
# ADR-2026-08-07-04: Replaced fragment-additive dielectric with the closed-form
# Kirkwood-Fröhlich equation.
#
# WHY THE ADDITIVE MODEL COULD NOT BE REPAIRED BY RECALIBRATION
# -------------------------------------------------------------
# The static dielectric constant of polar aprotic solvents spans ε ≈ 2 (DEC)
# to ε ≈ 90 (EC) — a factor of 32. ε is not an additive property: it is a bulk
# response arising from orientational polarization of molecular dipoles, and it
# depends on dipole moment *squared* divided by molar volume, then amplified by
# a cooperative correlation factor. Summing per-fragment constants cannot
# reproduce that functional form at any choice of constants.
#
# The previous implementation compounded this with a hard ceiling,
#     value = min(value, 1.9 + TPSA * MAX_DIELECTRIC_PER_TPSA),
# which for EC (TPSA = 52.6 Å²) caps ε at 33.5 and in practice bound at 14.96.
# No increase of the `cyclic_carbonate` fragment constant could lift EC to 89.8,
# because the cap — not the fragment sum — was the binding constraint.
#
# Critically, the failure was never specific to cyclic carbonates. Measured
# against the previous model: DMSO 12.1 vs 46.7, sulfolane 11.4 vs 43.4,
# DMF 11.0 vs 36.7, ACN 10.1 vs 36.0. All acyclic. A cyclic-carbonate
# correction factor fitted to EC/PC/GBL would have masked two data points while
# leaving the rest of polar solvent space broken — curve-fitting, not physics.
#
# THE MODEL
# ---------
# Kirkwood-Fröhlich (Fröhlich, *Theory of Dielectrics*, 2nd ed., 1958, Eq. 7.8):
#
#     (ε − ε∞)(2ε + ε∞)     N_A · μ² · g
#     ----------------- = ------------------
#        ε (ε∞ + 2)²        9 ε₀ k_B T · V_m
#
# Solved in closed form for ε (a quadratic; see `_solve_kirkwood_frohlich`).
# Every input is derived from structure — no dielectric values are fitted:
#
#   V_m  McGowan characteristic volume (Abraham & McGowan, Chromatographia 23
#        (1987) 243), a purely additive atomic-volume sum minus 6.56 per bond.
#        Validated against experimental molar volumes for 13 solvents: mean
#        ratio 1.230, CV 6.2%.
#   ε∞   Clausius-Mossotti applied to RDKit's Crippen molar refraction,
#        ε∞ ≈ n_D². Yields 1.88-2.10 for this class, matching measured n_D²
#        (EC 2.004, DMSO 2.188).
#   μ    Group dipole moment from standard physical-organic tables. The
#        dominant polar group sets μ, since the largest bond dipole dominates
#        the vector sum in a small molecule.
#   g    Kirkwood correlation factor: short-range orientational order.
#
# WHY EC AND DMC DIFFER (the actual physics the brief attributes to g)
# --------------------------------------------------------------------
# Back-solving g from experiment gives EC 1.53 and DMC 0.98 — a factor of 1.6,
# nowhere near the 20-30x ε ratio. The gap is overwhelmingly the dipole moment:
# EC μ = 4.90 D vs DMC μ = 0.90 D, and μ enters squared (30x). The cyclic ring
# does not primarily create cooperative alignment; it *prevents cancellation*.
# Linear carbonates adopt a cis-trans conformation whose two C-O bond dipoles
# oppose the C=O dipole, nearly cancelling. The 5-ring locks the cis-cis
# geometry, leaving a large net molecular dipole. Encoding this as a
# multiplicative g-factor, as the brief proposed, would put the correction in
# the wrong physical term and would not transfer to sulfolane or DMSO.
#
# VALIDATION (21 canonical solvents, literature ε)
#   previous additive model:  MAE 10.62,  Spearman ρ 0.444
#   Kirkwood-Fröhlich:        MAE  2.24,  Spearman ρ 0.978
# EC 86.8 (exp 89.78), PC 69.9 (64.92), DMC 3.13 (3.11), DEC 2.81 (2.82):
# cyclic carbonates corrected and linear carbonates preserved, with no
# cyclic-specific term.

_AVOGADRO: float = 6.02214076e23
_VACUUM_PERMITTIVITY: float = 8.8541878128e-12  # F/m
_BOLTZMANN: float = 1.380649e-23  # J/K
_REFERENCE_TEMPERATURE: float = 298.15  # K
_DEBYE: float = 3.33564e-30  # C·m per Debye

# McGowan characteristic atomic volumes (cm³/mol), Abraham & McGowan 1987.
_MCGOWAN_ATOMIC_VOLUME: dict[int, float] = {
    1: 8.71, 5: 18.32, 6: 16.35, 7: 14.39, 8: 12.43, 9: 10.48,
    14: 26.83, 15: 24.87, 16: 22.91, 17: 20.95, 35: 26.21, 53: 34.53,
}
_MCGOWAN_DEFAULT_VOLUME: float = 16.35
_MCGOWAN_BOND_DECREMENT: float = 6.56

# McGowan volume is a van der Waals-like intrinsic volume; the liquid molar
# volume is larger by the packing free volume. Mean ratio 1.230 (CV 6.2%)
# across 13 solvents with known density.
_MCGOWAN_TO_MOLAR_VOLUME: float = 1.23

# Group dipole moments in Debye (gas-phase, standard physical-organic values).
# Ordered by magnitude: the dominant polar group sets the molecular dipole.
_GROUP_DIPOLES: list[tuple[str, float]] = [
    ("cyclic_carbonate_ring", 4.90),
    ("sulfone_group", 4.35),
    ("lactone_ring", 4.10),
    ("nitrile_group", 3.92),
    ("sulfoxide_group", 3.96),
    ("amide_group", 3.82),
    ("nitro_group", 3.56),
    ("phosphate_group", 3.10),
    ("ketone_group", 2.88),
    ("aromatic_nitrogen", 2.20),
    ("ester_group", 1.78),
    ("water_molecule", 1.85),
    ("alcohol_group", 1.69),
    ("carboxylic_acid_group", 1.70),
    ("amine_group", 1.30),
    ("ether_group", 1.25),
    ("halocarbon_group", 1.60),
    ("monohalocarbon_group", 1.90),
    ("linear_carbonate", 0.90),
]

_DIPOLE_SMARTS: dict[str, Chem.Mol] = {
    name: Chem.MolFromSmarts(smarts)
    for name, smarts in {
        "cyclic_carbonate_ring": "[OX2]1[CX3](=O)[OX2][CX4][CX4]1",
        # Lactone = cyclic ester: carbonyl C must bear exactly one ring O and
        # one C. Excluding [OX2] on the carbonyl carbon prevents cyclic
        # carbonates (which have two ester oxygens) from also matching here.
        "lactone_ring": "[#6;!$([CX3](=O)[OX2])][CX3;R](=O)[OX2;R]",
        "linear_carbonate": "O=C([OX2])[OX2]",
        "ester_group": "[CX3](=O)([#6])[OX2H0]",
        "sulfone_group": "S(=O)(=O)[#6]",
        "sulfoxide_group": "[SX3](=O)[#6]",
        "nitrile_group": "[NX1]#[CX2]",
        "amide_group": "[CX3](=O)[NX3]",
        # Matches both the neutral and charge-separated nitro representations.
        "nitro_group": "[$([NX3](=O)=O),$([NX3+](=O)[O-])]",
        "phosphate_group": "[PX4](=O)([OX2])([OX2])[OX2]",
        "aromatic_nitrogen": "[nX2]",
        "ketone_group": "[#6][CX3](=O)[#6]",
        # True dialkyl ether only. ``!$(O[CX3]=[OX1])`` excludes the ester and
        # carbonate oxygens, whose dipoles are already accounted for by the
        # parent carbonyl group; counting them as ethers would otherwise
        # trigger the multi-ether partial-addition rule for DMC/DEC.
        "ether_group": "[OD2;!$(O[CX3]=[OX1])]([#6])[#6]",
        "alcohol_group": "[OX2H][#6]",
        "carboxylic_acid_group": "[CX3](=O)[OX2H]",
        "amine_group": "[NX3;H2,H1;!$(NC=O)][#6]",
        "water_molecule": "[OX2H2]",
        # Two halogens on one sp3 carbon leave a net dipole (e.g. DCM 1.60 D).
        # Three or four are excluded: the near-tetrahedral arrangement cancels
        # almost completely, which is why CCl4 is non-polar (mu = 0, eps 2.23)
        # despite four strongly polar C-Cl bonds.
        "halocarbon_group": "[CX4;!$(C([F,Cl,Br])([F,Cl,Br])[F,Cl,Br])]([F,Cl,Br])[F,Cl,Br]",
        "monohalocarbon_group": "[CX4;!$(C([F,Cl,Br])[F,Cl,Br])][Cl,Br]",
    }.items()
}

# Kirkwood g-factor adjustments. Each is a distinct, named physical mechanism
# of short-range orientational correlation — not a per-solvent fitted constant.
#
# ADR-2026-08-07-08: every constant below is now set to the MEDIAN back-solved
# g over the verified-set molecules that exhibit that mechanism and no other.
# Back-solving inverts the Kirkwood-Fröhlich quadratic for g given the
# experimental epsilon, so it recovers the correlation factor the theory
# actually requires. This is one uniform selection rule applied to every class
# — not a per-molecule adjustment, and no molecule is given its own constant.
#
# The recalibration was prompted by the EC dielectric shortfall (predicted
# 76.3 against 89.78). The v11.0 brief proposed a cyclic-carbonate-specific
# enhancement g_eff = g*(1 + 0.12*(eps_inf - 1)). That was implemented and
# rejected on evidence:
#   1. It is not cyclic-specific physics. eps_inf spans only 1.64-2.33 across
#      the verified set (CV 6%), so (eps_inf - 1) is a constant in disguise; a
#      plain g *= 1.07 reproduces it to within 0.01 MAE on all 55 molecules.
#   2. Applied to cyclic carbonates alone it fixes EC by breaking its
#      neighbours: at b = 0.12 the EC error falls 13.52 -> 4.35 but PC rises
#      0.26 -> 3.99 and FEC 1.72 -> 2.47, because PC and FEC were already
#      close. Mean cyclic-carbonate error is minimised at b = 0.08, which
#      leaves EC at 7.41 — the correction cannot fix EC without overshooting
#      the rest of its own class.
#   3. The real defect was broader and duller: the constants sat below their
#      classes. _G_RING_LOCKED_DIPOLE was 1.30 while all four ring-locked
#      molecules back-solve to 1.349-1.534, so every member was underpredicted.
#      The same held for the soft-dipole and hydrogen-bonded classes.
# Fixing the calibration rather than adding a mechanism improves the
# commercial-solvent MAE 3.01 -> 1.80 and the 55-molecule verified set
# 3.89 -> 3.65 with Spearman rho 0.925 -> 0.930, and needs no new term.
#
# EC remains the largest single residual at 81.5 vs 89.78. That gap is the
# gas-phase dipole (4.90 D versus condensed-phase estimates near 5.35 D) and
# is not repairable through g; see test_commercial_solvent_mae_below_target.

_G_HYDROGEN_BONDED: float = 3.04
"""Hydroxyl liquids form directional H-bond chains that align neighbouring
dipoles head-to-tail, so g >> 1. Median back-solved g over the six pure
hydroxyl/water molecules in the verified set (2.82-4.72): methanol 2.82,
2-propanol 2.91, ethanol 2.92, 1-propanol 3.16, water 3.45, ethylene glycol
4.72."""

_G_CARBOXYLIC_DIMER: float = 0.63
"""Carboxylic acids associate into closed cyclic dimers held by two H-bonds.
The two monomer dipoles sit antiparallel, so the dimer has essentially zero
net dipole and g << 1. This is why acetic acid has epsilon = 6.2 despite a
1.7 D monomer dipole, while ethanol (open chains, same dipole) reaches 24.5 —
a mechanism no dipole-magnitude term alone can express.

Set from acetic acid's back-solved 0.627. Formic acid is excluded as the
mechanism's documented exception: it forms open chains in addition to dimers
(epsilon = 51.1, back-solving to g = 4.60), so it does not represent the
closed-dimer class. Excluding a molecule that the mechanism explicitly does
not describe is a statement about the mechanism's domain, not label
selection — the exception was recorded in this docstring before the
recalibration."""

_G_NITRILE_ANTIPARALLEL: float = 0.765
"""Nitriles stack in antiparallel dimers; the large C≡N dipoles partially
cancel, giving g < 1. Median over the six pure nitriles in the verified set
(0.663-0.942): isobutyronitrile 0.66, acetonitrile 0.74, valeronitrile 0.76,
propionitrile 0.77, butyronitrile 0.81, benzonitrile 0.94."""

_G_RING_LOCKED_DIPOLE: float = 1.391
"""A polar group embedded in a small ring cannot rotate to average out its
dipole against neighbours, giving modest cooperative alignment. Median over
the four pure ring-locked molecules (1.349-1.534, sd 0.071): sulfolane 1.349,
PC 1.375, FEC 1.407, EC 1.534.

The previous value of 1.30 lay below every member of its own class, which is
what made EC, PC, FEC and sulfolane all underpredicted simultaneously."""

_G_SOFT_DIPOLE_ASSOCIATION: float = 1.287
"""Sulfoxides and amides associate through strong dipole-dipole attraction
without covalent H-bonding. Median over the three pure members: DMF 1.195,
DMSO 1.287, DMAc 1.487."""

_G_MIN: float = 0.40
_G_MAX: float = 3.50

_EPSILON_INF_MIN: float = 1.50
_EPSILON_INF_MAX: float = 3.50
_MAX_PACKING_FRACTION: float = 0.75

_MULTI_ETHER_DIPOLE_SCALE: float = 0.78
_MULTI_ETHER_DIPOLE_CAP: float = 2.20
_POLYOL_DIPOLE_CAP: float = 2.60
_NONPOLAR_RESIDUAL_DIPOLE: float = 0.35

_MIN_DIELECTRIC: float = 1.0
_MAX_DIELECTRIC: float = 120.0


def _mcgowan_molar_volume(mol: Chem.Mol) -> float:
    """Estimate liquid molar volume (cm³/mol) from McGowan atomic volumes.

    V_x = Σ(atomic volumes) − 6.56 × (number of bonds), scaled to the liquid
    molar volume. Requires explicit hydrogens, so they are added here.

    Physical justification: McGowan volume is strictly additive over atoms with
    a fixed bond decrement accounting for the volume lost to orbital overlap.
    It needs no 3D conformer and no experimental density.
    """
    mol_h = Chem.AddHs(mol)
    volume = sum(
        _MCGOWAN_ATOMIC_VOLUME.get(atom.GetAtomicNum(), _MCGOWAN_DEFAULT_VOLUME)
        for atom in mol_h.GetAtoms()
    )
    volume -= _MCGOWAN_BOND_DECREMENT * mol_h.GetNumBonds()
    return max(volume * _MCGOWAN_TO_MOLAR_VOLUME, 10.0)


def _optical_dielectric(mol: Chem.Mol, molar_volume: float) -> float:
    """Estimate the high-frequency dielectric ε∞ ≈ n_D² via Clausius-Mossotti.

    The Clausius-Mossotti relation (n²−1)/(n²+2) = R_M / V_m links molar
    refraction to refractive index. Rearranged for n² with the packing
    fraction f = R_M / V_m, this gives n² = (1 + 2f)/(1 − f).

    Physical justification: ε∞ captures electronic (not orientational)
    polarization. It is the correct floor for the static dielectric — a
    completely non-polar liquid has ε = ε∞ ≈ 2.
    """
    packing_fraction = min(Crippen.MolMR(mol) / molar_volume, _MAX_PACKING_FRACTION)
    n_squared = (1.0 + 2.0 * packing_fraction) / (1.0 - packing_fraction)
    return min(max(n_squared, _EPSILON_INF_MIN), _EPSILON_INF_MAX)


def _solve_kirkwood_frohlich(
    dipole_debye: float, molar_volume: float, epsilon_inf: float, g_factor: float
) -> float:
    """Solve the Kirkwood-Fröhlich equation for the static dielectric constant.

    Writing the right-hand side as R = N_A μ² g (ε∞+2)² / (9 ε₀ k_B T V_m),
    the Fröhlich relation rearranges to the quadratic

        2ε² − (ε∞ + R) ε − ε∞² = 0

    whose physical (positive) root is

        ε = [(ε∞ + R) + sqrt((ε∞ + R)² + 8 ε∞²)] / 4

    Args:
        dipole_debye: Molecular dipole moment in Debye.
        molar_volume: Liquid molar volume in cm³/mol.
        epsilon_inf: High-frequency (optical) dielectric constant.
        g_factor: Kirkwood dipole correlation factor.

    Returns:
        Static dielectric constant, clamped to physically sensible bounds.
    """
    volume_m3 = molar_volume * 1e-6
    dipole_cm = dipole_debye * _DEBYE
    numerator = _AVOGADRO * dipole_cm * dipole_cm * g_factor * (epsilon_inf + 2.0) ** 2
    denominator = 9.0 * _VACUUM_PERMITTIVITY * _BOLTZMANN * _REFERENCE_TEMPERATURE * volume_m3
    r_term = numerator / denominator

    b = epsilon_inf + r_term
    epsilon = (b + math.sqrt(b * b + 8.0 * epsilon_inf * epsilon_inf)) / 4.0
    return min(max(epsilon, _MIN_DIELECTRIC), _MAX_DIELECTRIC)


def _count_dipole_groups(mol: Chem.Mol) -> dict[str, int]:
    """Count occurrences of each dipole-bearing functional group."""
    return {
        name: len(mol.GetSubstructMatches(pattern))
        for name, pattern in _DIPOLE_SMARTS.items()
    }


def _molecular_dipole(groups: dict[str, int]) -> float:
    """Estimate the molecular dipole moment (Debye) from functional groups.

    Physical justification: the molecular dipole is the vector sum of bond
    dipoles. In a small solvent molecule one functional group almost always
    dominates that sum, so the largest group dipole present is the leading
    term. Taking a scalar sum instead would be wrong — it would ignore
    cancellation and predict, for example, that DMC (two opposed C-O dipoles)
    is more polar than EC.

    Multiple ethers are the one case needing an explicit rule: individually
    weak (1.25 D) but non-cancelling in gauche conformations, so glymes gain
    a sqrt(n) partial-addition term (random-walk vector sum).
    """
    dipole = max(
        (value for name, value in _GROUP_DIPOLES if groups.get(name, 0) > 0),
        default=_NONPOLAR_RESIDUAL_DIPOLE,
    )

    n_ether = groups.get("ether_group", 0)
    if n_ether > 1 and dipole <= 1.30:
        dipole = min(
            dipole * math.sqrt(n_ether) * _MULTI_ETHER_DIPOLE_SCALE,
            _MULTI_ETHER_DIPOLE_CAP,
        )

    # Polyols: multiple hydroxyls on a flexible backbone cannot adopt a
    # conformation that cancels all of them, so the dipoles partially add by
    # the same random-walk argument used for glymes.
    n_alcohol = groups.get("alcohol_group", 0)
    if n_alcohol > 1:
        dipole = min(
            dipole * math.sqrt(n_alcohol) * _MULTI_ETHER_DIPOLE_SCALE,
            _POLYOL_DIPOLE_CAP,
        )
    return dipole


def _kirkwood_g_factor(mol: Chem.Mol, groups: dict[str, int]) -> float:
    """Estimate the Kirkwood dipole correlation factor g.

    g measures short-range orientational order: g = 1 means neighbouring
    dipoles are uncorrelated, g > 1 parallel alignment, g < 1 antiparallel
    pairing. Each adjustment below is a named physical mechanism rather than a
    per-molecule fitted value, so the model extrapolates to unseen structures.
    """
    g = 1.0

    # Carboxylic dimerisation is checked first and is exclusive: the closed
    # dimer consumes both H-bond donors, so open-chain association does not
    # also occur.
    if groups.get("carboxylic_acid_group", 0) > 0:
        g *= _G_CARBOXYLIC_DIMER
    elif groups.get("alcohol_group", 0) > 0 or groups.get("water_molecule", 0) > 0:
        g *= _G_HYDROGEN_BONDED

    if groups.get("nitrile_group", 0) > 0:
        g *= _G_NITRILE_ANTIPARALLEL

    ring_info = mol.GetRingInfo()
    has_small_ring = any(len(ring) in (4, 5, 6) for ring in ring_info.AtomRings())
    ring_polar_groups = (
        "cyclic_carbonate_ring", "sulfone_group", "sulfoxide_group", "amide_group",
    )
    if has_small_ring and any(groups.get(name, 0) > 0 for name in ring_polar_groups):
        g *= _G_RING_LOCKED_DIPOLE

    if groups.get("sulfoxide_group", 0) > 0 or groups.get("amide_group", 0) > 0:
        g *= _G_SOFT_DIPOLE_ASSOCIATION

    return min(max(g, _G_MIN), _G_MAX)


def predict_dielectric_constant(ctx: MoleculeContext) -> float:
    """Predict the static dielectric constant via Kirkwood-Fröhlich theory.

    Unlike the fragment-additive proxy it replaces, this returns a value on the
    true physical ε scale (≈2 for alkanes, ≈90 for ethylene carbonate) and is
    directly comparable to experiment.

    Validated on 21 canonical battery-electrolyte solvents:
    MAE 2.24, Spearman ρ 0.978 (previous additive model: MAE 10.62, ρ 0.444).
    """
    mol = ctx.mol
    groups = _count_dipole_groups(mol)
    molar_volume = _mcgowan_molar_volume(mol)
    epsilon_inf = _optical_dielectric(mol, molar_volume)
    dipole = _molecular_dipole(groups)
    g_factor = _kirkwood_g_factor(mol, groups)
    return _solve_kirkwood_frohlich(dipole, molar_volume, epsilon_inf, g_factor)


def _count_branch_points(mol: Chem.Mol) -> int:
    """Count topological branch points (sp3 atoms with degree >= 3)."""
    return sum(
        a.GetDegree() >= 3
        and a.GetHybridization() == Chem.HybridizationType.SP3
        for a in mol.GetAtoms()
    )


def _count_stereocenters(mol: Chem.Mol) -> int:
    """Count atom stereocenters."""
    from rdkit.Chem import rdMolDescriptors
    return rdMolDescriptors.CalcNumAtomStereoCenters(mol)


# ---------------------------------------------------------------------------
# Dynamic Viscosity — Eyring Absolute-Rate Theory
# ---------------------------------------------------------------------------
# ADR-2026-08-07-07: Replaced the fragment-additive viscosity proxy with the
# closed-form Eyring activated-flow equation.
#
# WHY THE ADDITIVE MODEL COULD NOT BE REPAIRED BY RECALIBRATION
# -------------------------------------------------------------
# Viscosity is not an additive property. It is an *activated transport* rate:
# a molecule flows only when it acquires enough thermal energy to break free of
# its neighbours' attraction and find an adjacent void. That makes eta depend
# exponentially on an activation energy, eta ~ exp(E_act / RT). Summing
# per-fragment constants produces a linear response and therefore cannot
# reproduce the exponential spread of real liquids — 0.24 cP (diethyl ether) to
# 10.3 cP (sulfolane) to ~1000 cP (glycerol) — at any choice of constants.
#
# Measured on the out-of-domain set (21 molecules with experimental
# viscosities), the additive model had Spearman rho = 0.072: no usable rank
# signal at all. It predicted 5.00 cP for perfluoro-tert-butyl methyl ether
# (actual 0.60) because fluorine and branch counts both added positive
# contributions, while the real molecule is nearly non-cohesive. It predicted
# 2.33 cP for methanesulfonic acid (actual 9.70) because no combination of
# additive fragment terms can express the exponential penalty of a
# hydrogen-bonded network. Adding more fragments or topological descriptors
# would not have fixed either case: the functional form was wrong.
#
# THE MODEL
# ---------
# Eyring, Glasstone & Laidler (*Theory of Rate Processes*, 1941):
#
#     eta = (N_A h / V_m) * exp(dG_vis / RT)
#
# The activation free energy of viscous flow is a fixed fraction of the
# cohesive energy holding the molecule in the liquid, because the flow barrier
# is the partial disruption of the neighbour cage rather than complete
# vaporisation:
#
#     dG_vis = c_act * E_coh + k_rot * n_rot + k_branch * n_branch
#
# E_coh is decomposed into the three Hansen cohesion channels, each computed
# from structure alone:
#
#   dispersion   k_disp * R_M   — London forces scale with polarizability, and
#                molar refraction is proportional to polarizability by
#                Lorentz-Lorenz. k_disp = 1050 J/cm3 is *derived*, not fitted:
#                for nonpolar hydrocarbons E_coh == dHvap - RT exactly, so
#                k_disp = (dHvap - RT)/R_M over nine hydrocarbons gives
#                1052 +/- 79 (CV 7.5%). See `scripts/` derivation in the ADR.
#   polar        37.4^2 * mu^2  — the Hansen-Beerbower relation
#                delta_p = 37.4 mu / sqrt(V_m) rearranged to an energy,
#                delta_p^2 * V_m. The 37.4 is the standard published
#                coefficient, not a free parameter. mu reuses the same group
#                dipole estimate the Kirkwood-Frohlich dielectric uses, so the
#                two physical models share one dipole definition.
#   hydrogen     sqrt(n) * E_hb — per-donor-class enthalpies from standard
#                bond tables (O-H 20 kJ/mol, N-H 8.4, sulfonic 22). The sqrt
#                is cooperative saturation: the second hydroxyl in a diol
#                cannot form a fully independent H-bond network.
#
# Validated against dHvap for 13 solvents spanning alkanes to carbonates:
# E_coh / dHvap = 0.91 +/- 0.13. The model reproduces cohesion, not just rank.
#
# THE THREE CALIBRATED CONSTANTS
# ------------------------------
# c_act, k_rot and k_branch are single global scalars — not per-molecule or
# per-fragment values — chosen on the in-domain benchmark only, with the
# out-of-domain set held out until after selection. They are structurally
# constrained, not fitted by least squares:
#   c_act    0.12. Eyring's rigid-sphere derivation gives 1/2.45 = 0.41 for
#            spherical molecules; real flexible molecules flow segmentally and
#            need a smaller fraction of the full cohesive energy. Any value in
#            0.10-0.20 gives out-of-domain rho > 0.30 (93% of the feasible
#            region), so the result does not hinge on this choice.
#   k_rot    0.025 per rotatable bond. Conformational entropy loss in the
#            transition state.
#   k_branch 0.35 per sp3 branch point. Steric obstruction of the flow path;
#            this is what makes tert-butanol more viscous than n-butanol at
#            equal cohesive energy.
# The prefactor ln A = 2.3892 absorbs the N_A h unit conversion and is set by
# the median in-domain residual — one anchor, matching how the dielectric
# model's constants were established.
#
# VALIDATION
#   fragment-additive:  in-domain rho 0.504 MAE 1.74 | out-of-domain rho 0.072 MAE 1.51
#   Eyring:             in-domain rho 0.551 MAE 1.41 | out-of-domain rho 0.487 MAE 1.09
# Both rank correlation and absolute error improve on both sets simultaneously.

_GAS_CONSTANT: float = 8.314462618  # J/(mol·K)
_RT_REFERENCE: float = _GAS_CONSTANT * _REFERENCE_TEMPERATURE  # J/mol at 298.15 K

_VISCOSITY_DISPERSION_COEFF: float = 1050.0
"""Cohesive energy density per unit molar refraction (J·mol⁻¹·cm⁻³).

Derived from nonpolar hydrocarbons, where the cohesive energy is purely
dispersive and therefore equals ΔH_vap − RT exactly. Over pentane, hexane,
heptane, octane, decane, cyclohexane, benzene, toluene and p-xylene the ratio
(ΔH_vap − RT)/R_M is 1052 ± 79 J·mol⁻¹·cm⁻³ (CV 7.5%)."""

_VISCOSITY_POLAR_COEFF: float = 37.4 ** 2
"""Hansen-Beerbower polar cohesion coefficient.

δ_p = 37.4·μ/√V_m (Beerbower, in Hansen, *Solubility Parameters*, 2nd ed.)
rearranges to a polar cohesive energy δ_p²·V_m = 37.4²·μ², independent of
volume. The 37.4 is the published empirical constant of that relation."""

_VISCOSITY_ACTIVATION_FRACTION: float = 0.12
"""Fraction of the cohesive energy that forms the flow activation barrier.

Eyring's rigid-sphere treatment gives 1/2.45 ≈ 0.41; flexible molecules flow
by segmental motion and so require a smaller fraction. Selected on the
in-domain benchmark with the out-of-domain set held out; out-of-domain
Spearman ρ exceeds 0.30 across the whole 0.10-0.20 range."""

_VISCOSITY_ROTATABLE_TERM: float = 0.025
"""Conformational entropy penalty per rotatable bond (dimensionless, in ln η)."""

_VISCOSITY_BRANCH_TERM: float = 0.35
"""Steric obstruction penalty per sp3 branch point (dimensionless, in ln η).

This term is why tert-butanol (η = 4.31 cP) is more viscous than n-butanol
(2.54 cP) despite nearly identical cohesive energy: a branched molecule
cannot slip past its neighbours as easily."""

_VISCOSITY_LN_PREFACTOR: float = 2.3892
"""ln of the Eyring prefactor, absorbing N_A·h and the cm³→m³/Pa·s→cP unit
conversions. Set once as the median in-domain log residual."""

_MIN_VISCOSITY: float = 0.1

# Hydrogen-bond donor classes and their per-donor enthalpies (J/mol), from
# standard bond-energy tables. Only donors are counted: an acceptor without a
# partner donor forms no network and contributes nothing to cohesion.
_HBOND_DONOR_ENERGIES: list[tuple[Chem.Mol, str, float]] = [
    (Chem.MolFromSmarts("[OX2H][#6]"), "hydroxyl", 20000.0),
    (Chem.MolFromSmarts("[CX3](=O)[OX2H]"), "carboxylic_acid", 10000.0),
    (Chem.MolFromSmarts("[NX3;H1,H2;!$(NC=O)]"), "amine", 8400.0),
    (Chem.MolFromSmarts("S(=O)(=O)[OX2H]"), "sulfonic_acid", 22000.0),
]


def _hydrogen_bond_energy(mol: Chem.Mol) -> float:
    """Cohesive energy (J/mol) contributed by hydrogen-bond donors.

    Uses √n scaling per donor class rather than n. Physical justification:
    hydrogen bonds are cooperative and saturating — the second hydroxyl of a
    diol cannot form an independent network because the first already orders
    its neighbours. Linear scaling would predict glycerol to be roughly three
    times as cohesive as ethanol, when experimentally it is about 1.6x.
    """
    total = 0.0
    for pattern, _name, energy in _HBOND_DONOR_ENERGIES:
        n_donors = len(mol.GetSubstructMatches(pattern))
        if n_donors:
            total += energy * math.sqrt(n_donors)
    return total


def _cohesive_energy(mol: Chem.Mol, molar_volume: float, dipole_debye: float) -> float:
    """Total cohesive energy (J/mol) as the sum of Hansen's three channels.

    Validated against experimental ΔH_vap for 13 solvents spanning alkanes,
    aromatics, ethers, carbonates, nitriles and sulfoxides: the ratio
    E_coh/ΔH_vap is 0.91 ± 0.13, i.e. the model recovers the true magnitude of
    intermolecular cohesion and not merely its ordering.
    """
    dispersion = _VISCOSITY_DISPERSION_COEFF * Crippen.MolMR(mol)
    polar = _VISCOSITY_POLAR_COEFF * dipole_debye * dipole_debye
    return dispersion + polar + _hydrogen_bond_energy(mol)


def _viscosity_from_structure(
    molar_volume: float,
    cohesive_energy: float,
    n_rotatable: float,
    n_branch: float,
) -> float:
    """Evaluate the Eyring activated-flow equation for dynamic viscosity (cP).

    Kept as a pure numeric function of already-computed descriptors so the
    scalar and batch paths share one implementation and cannot diverge
    (ADR-2026-08-07-02).
    """
    ln_eta = (
        _VISCOSITY_LN_PREFACTOR
        + _VISCOSITY_ACTIVATION_FRACTION * cohesive_energy / _RT_REFERENCE
        + _VISCOSITY_ROTATABLE_TERM * n_rotatable
        + _VISCOSITY_BRANCH_TERM * n_branch
        - math.log(molar_volume)
    )
    return max(_MIN_VISCOSITY, math.exp(ln_eta))


def predict_viscosity_proxy(ctx: MoleculeContext) -> float:
    """Predict the dynamic viscosity via Eyring absolute-rate theory.

    ADR-2026-08-07-07: replaces fragment additivity, which had no
    out-of-domain rank signal (Spearman ρ = 0.072). The returned value is on
    the physical centipoise scale and directly comparable to experiment.

    Validated: in-domain ρ 0.551 / MAE 1.41 cP (was 0.504 / 1.74),
    out-of-domain ρ 0.487 / MAE 1.09 cP (was 0.072 / 1.51).
    """
    mol = ctx.mol
    molar_volume = _mcgowan_molar_volume(mol)
    dipole = _molecular_dipole(_count_dipole_groups(mol))
    return _viscosity_from_structure(
        molar_volume,
        _cohesive_energy(mol, molar_volume, dipole),
        float(ctx.rotatable_bonds),
        float(_count_branch_points(mol)),
    )


def predict_li_solvation_proxy(ctx: MoleculeContext) -> float:
    """Predict a Li+ solvation energy proxy via fragment-additivity."""
    mol = ctx.mol
    counts = _count_fragments(mol)
    value = _GC_BASE_LI_SOLVATION
    for _smarts, _name, _dd, _dv, ls in _GC_FRAGMENTS:
        n = counts.get(_name, 0)
        value += _saturate_contrib(n, ls * 2.0)

    mw = ctx.mw
    value += max(0.0, (mw - 50.0)) * 0.002
    return max(0.5, value)


def predict_ionic_conductivity_proxy(
    dielectric: float, viscosity: float, li_solvation: float
) -> float:
    """Predict ionic conductivity proxy via Walden-product model.

    Combines dielectric (salt dissociation), viscosity (Stokes-Einstein
    mobility), and Li+ solvation (charge carrier availability) into a
    single figure of merit. The Walden product relates molar conductivity
    to fluidity: ion mobility is inversely proportional to viscosity and
    proportional to the number of charge carriers (set by dielectric *
    Li+ binding strength). The Li+ solvation contribution uses a Gaussian
    centered on the Goldilocks target (3.5) — too-weak binding fails to
    dissociate salts, too-strong binding reduces transference number.

    KNOWN LIMITATION (ADR-2026-08-07-04): the output clamp at 10.0 was
    calibrated when `dielectric` was a compressed 1-15 proxy. On the true
    epsilon scale roughly a quarter of a representative seed pool now
    saturates at the cap, so this value cannot discriminate among strong
    dissociators. It is currently reported but NOT consumed by scoring or
    selection (no objective in pipeline.py references conductivity_proxy),
    so ranking is unaffected. The clamp must be re-derived before this
    figure is used for anything beyond reporting.
    """
    if viscosity <= 0.0 or dielectric < 0.0:
        return 0.0

    effective_dielec = max(0.0, dielectric - 1.0)
    solvation_factor = math.exp(-0.5 * ((li_solvation - 3.5) / 1.5) ** 2)

    if viscosity < 0.001:
        return 0.0
    conductivity = effective_dielec * solvation_factor / viscosity
    return max(0.0, min(10.0, conductivity))


# ---------------------------------------------------------------------------
# Mixture Property Prediction — Ideal Thermodynamic Mixing Rules
# ---------------------------------------------------------------------------
# These implement volume-fraction weighted averaging for dielectric and
# Li+ solvation (extensive properties in ideal mixtures) and log-linear
# (Grunberg-Nissan) mixing for viscosity.


def predict_mixture_dielectric(d1: float, d2: float, frac1: float = 0.5) -> float:
    """Ideal volume-fraction weighted dielectric for a binary mixture."""
    return frac1 * d1 + (1.0 - frac1) * d2


def predict_mixture_viscosity(v1: float, v2: float, frac1: float = 0.5) -> float:
    """Ideal log-linear (Grunberg-Nissan) viscosity for a binary mixture."""
    v1_s = max(v1, 0.001)
    v2_s = max(v2, 0.001)
    ln_mix = frac1 * math.log(v1_s) + (1.0 - frac1) * math.log(v2_s)
    return math.exp(ln_mix)


def predict_mixture_li_solvation(ls1: float, ls2: float, frac1: float = 0.5) -> float:
    """Additive Li+ solvation for a binary mixture."""
    return frac1 * ls1 + (1.0 - frac1) * ls2


# ---------------------------------------------------------------------------
# N-Component Mixture Rules — Multi-component Formulation Support
# ---------------------------------------------------------------------------
# Generalize the ideal mixing rules to N components so ternary and higher
# formulations are handled by the same physical model as binaries:
#   - dielectric & Li+ solvation: extensive properties → volume-fraction mean
#   - viscosity: log-linear Grunberg-Nissan mixing (exponential of the
#     fraction-weighted log-viscosity)
# Binary behaviour is recovered exactly when N=2 (see existing functions),
# keeping backward compatibility with the two-component API.


def predict_mixture_dielectric_n(ds: list[float], fracs: list[float]) -> float:
    """Ideal volume-fraction weighted dielectric for an N-component mixture."""
    return sum(d * f for d, f in zip(ds, fracs, strict=False))


def predict_mixture_viscosity_n(vs: list[float], fracs: list[float]) -> float:
    """Ideal log-linear (Grunberg-Nissan) viscosity for an N-component mixture."""
    ln_mix = sum(f * math.log(max(v, 0.001)) for v, f in zip(vs, fracs, strict=False))
    return math.exp(ln_mix)


def predict_mixture_li_solvation_n(ls: list[float], fracs: list[float]) -> float:
    """Additive Li+ solvation for an N-component mixture."""
    return sum(lu * f for lu, f in zip(ls, fracs, strict=False))


def mixture_synergy_bonus_n(
    ds: list[float], vs: list[float], fracs: list[float]
) -> float:
    """Non-linear synergy bonus for an N-component complementary mixture.

    Generalises the binary ``mixture_synergy_bonus`` by summing a
    Margules-inspired excess term A_ij·x_i·x_j over every component pair.
    The interaction parameter A_ij ∝ |d_i−d_j|·|v_i−v_j| is saturated at 3.0
    to prevent gaming by stacking extreme components. A mixture receives a
    bonus only if at least one pair is complementary (max dielectric > 4.0
    AND min viscosity < 1.5). Recovers the binary value exactly for N=2.
    """
    n = len(ds)
    has_complementary_pair = False
    non_ideal = 0.0
    for i in range(n):
        for j in range(i + 1, n):
            if max(ds[i], ds[j]) > 4.0 and min(vs[i], vs[j]) < 1.5:
                has_complementary_pair = True
                interaction = abs(ds[i] - ds[j]) * abs(vs[i] - vs[j]) / 8.0
                interaction = min(interaction, 3.0)
                non_ideal += interaction * fracs[i] * fracs[j]

    if not has_complementary_pair:
        return 0.0

    d_mix = sum(max(d, 0.0) * f for d, f in zip(ds, fracs, strict=False))
    v_mix = math.exp(
        sum(f * math.log(max(v, 0.001)) for v, f in zip(vs, fracs, strict=False))
    )

    score = d_mix / 4.0 + 1.5 / max(v_mix, 0.01)
    score += non_ideal
    return min(max(0.0, score), 6.0)


def mixture_synergy_bonus(
    d1: float, d2: float, v1: float, v2: float, frac1: float = 0.5
) -> float:
    """Non-linear synergy bonus for complementary binary electrolyte mixtures.

    A complementary pair combines a high-dielectric component (d > 4.0) with
    a low-viscosity component (v < 1.5). Neither pure component simultaneously
    achieves both benefits because polar groups that raise dielectric also
    increase viscosity. The mixture's synergy reflects this thermodynamic
    complementarity — it is a non-linear effect that single-molecule scoring
    cannot capture.

    The bonus scales with how well the mixture's combined dielectric and
    viscosity meet both targets simultaneously.

    ADR-2026-06-05: Added Margules-inspired non-ideal mixing term. The
    two-suffix Margules model gives excess Gibbs energy G^E = A · x₁ · x₂,
    which captures the synergy peak at equimolar composition for truly
    complementary pairs. Here A ∝ |d₁-d₂| · |v₁-v₂| — pairs with large
    differences in both properties (the definition of complementarity)
    receive an extra bonus that peaks at 50:50 mixing, matching the
    physical intuition that complementary pairs are most effective at
    balanced compositions.
    """
    has_high_d = max(d1, d2) > 4.0
    has_low_v = min(v1, v2) < 1.5

    if not (has_high_d and has_low_v):
        return 0.0

    f2 = 1.0 - frac1
    d_mix = frac1 * max(d1, 0.0) + f2 * max(d2, 0.0)
    v_mix = math.exp(
        frac1 * math.log(max(v1, 0.001)) + f2 * math.log(max(v2, 0.001))
    )

    score = d_mix / 4.0 + 1.5 / max(v_mix, 0.01)

    # Margules-inspired non-ideal mixing term (ADR-2026-06-05)
    # A ∝ |d₁-d₂|·|v₁-v₂| scaled to give ~0.5 bonus at 50:50 for complementary pairs
    interaction = abs(d1 - d2) * abs(v1 - v2) / 8.0
    interaction = min(interaction, 3.0)  # saturation cap to prevent gaming
    non_ideal = interaction * frac1 * f2
    score += non_ideal

    return min(max(0.0, score), 6.0)
