"""QuantumOracle — Real Quantum Chemistry for Frontier Orbitals.

HOMO/LUMO energies are global, delocalised quantum phenomena that CANNOT
be predicted by fragment-additivity.  This module provides a two-tier
quantum oracle:
  1. xTB (GFN2-xTB) via subprocess — fast semi-empirical QM (preferred)
  2. Topological Orbital Model (TOM) — conjugation-aware fallback

The fallback is based on the particle-in-a-box model for pi-electrons:
  E ∝ n²/L²  where L = conjugation length, n = electron count
with heteroatom perturbations from Hueckel theory.

Physical justification: The TOM is based on the particle-in-a-box model for
pi-electrons (E ∝ n²/L² where L = conjugation length, n = electron count) with
heteroatom perturbations from Hueckel theory. xTB (GFN2-xTB) via subprocess is
the preferred backend, achieving sub-1.0 eV MAE on the calibration set (45 DFT
references). TOM falls back to a closed-form analytic formula (no regression
model) with MAE ≈ 1.07 eV. Constants are calibrated against published DFT
references; historical tuning is documented in CHANGELOG.md.
"""

from __future__ import annotations

import atexit
import concurrent.futures
import contextlib
import logging
import math
import os
import re
import shutil
import subprocess
import tempfile

from rdkit import Chem

from aurelius.constants import NITRILE_PATTERN
from aurelius.types import MoleculeContext

logger = logging.getLogger(__name__)


def _find_xtb_binary() -> str | None:
    """Locate the xTB binary on the system PATH."""
    for candidate in ["xtb", "xtb_opt"]:
        with contextlib.suppress(Exception):
            result = subprocess.run(
                [candidate, "--version"],
                capture_output=True, text=True, timeout=5,
            )
            if result.returncode == 0:
                return candidate
    return None


# Module-level caches for xTB binary path and temp workspace
_XTB_BIN: str | None = _find_xtb_binary()
_HAS_XTB: bool = _XTB_BIN is not None
_XTB_BASE_TEMP: str | None = (
    tempfile.mkdtemp(prefix="aurelius_xtb_pool_") if _HAS_XTB else None
)


@atexit.register
def _cleanup_xtb_workspace() -> None:
    """Remove the shared xTB temp workspace on interpreter exit."""
    global _XTB_BASE_TEMP
    if _XTB_BASE_TEMP is not None and os.path.exists(_XTB_BASE_TEMP):
        shutil.rmtree(_XTB_BASE_TEMP, ignore_errors=True)
        _XTB_BASE_TEMP = None


def has_xtb() -> bool:
    """Return True if the xTB binary is available on PATH."""
    return _HAS_XTB


_N_CONFORMERS: int = 5
_N_TOP_CONFORMERS: int = 3
_BOLTZMANN_TEMP: float = 298.15
_R_GAS: float = 0.001987  # kcal/(mol*K)


def _generate_xyz(mol: Chem.Mol) -> str:
    """Generate an XYZ string from a molecule with a 3D conformer."""
    from rdkit.Chem import AllChem

    mol = Chem.RWMol(mol)
    mol.UpdatePropertyCache()
    with contextlib.suppress(Exception):
        mol = Chem.AddHs(mol)

    params = AllChem.ETKDGv3()
    params.randomSeed = 42
    result = AllChem.EmbedMolecule(mol, params)
    if result != 0:
        return _generate_xyz_geometry_optimized(mol)

    with contextlib.suppress(Exception):
        AllChem.UFFOptimizeMolecule(mol, maxIters=250)

    conf = mol.GetConformer()
    n_atoms = mol.GetNumAtoms()
    lines = [str(n_atoms), ""]
    for i in range(n_atoms):
        atom = mol.GetAtomWithIdx(i)
        symb = atom.GetSymbol()
        pos = conf.GetAtomPosition(i)
        lines.append(f"{symb} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}")
    return "\n".join(lines)


def _generate_multi_xyz(
    mol: Chem.Mol,
    n_conformers: int = _N_CONFORMERS,
    random_seed: int = 42,
) -> list[tuple[str, float]]:
    """Generate multiple conformers with UFF optimizations and energies.

    Uses ETKDGv3 with multiple random seeds to sample diverse conformer
    space. Each conformer is UFF-optimized and its UFF energy is returned.

    Physical justification: A single conformer generated by ETKDGv3 can
    be a high-energy, non-physical geometry that leads to garbage xTB/TOM
    predictions. Boltzmann weighting over multiple conformers stabilises
    predictions by down-weighting high-energy conformers and avoiding
    false-positive narrow gaps from strained geometries. This is especially
    important for flexible electrolyte molecules (e.g., glymes, long-chain
    carbonates) that have many accessible conformations in solution.

    Returns:
        List of (xyz_string, uff_energy_kcal) tuples, sorted by energy
        ascending (lowest energy first).
    """
    from rdkit.Chem import AllChem

    mol = Chem.RWMol(mol)
    mol.UpdatePropertyCache()
    with contextlib.suppress(Exception):
        mol = Chem.AddHs(mol)

    results: list[tuple[str, float]] = []

    for i in range(n_conformers):
        mol_copy = Chem.RWMol(mol)
        params = AllChem.ETKDGv3()
        params.randomSeed = random_seed + i * 7
        result = AllChem.EmbedMolecule(mol_copy, params)
        if result != 0:
            continue
        try:
            ff = AllChem.UFFGetMoleculeForceField(mol_copy)
            if ff is None:
                continue
            converged = ff.Minimize(maxIts=500)
            energy = ff.CalcEnergy()
        except Exception:
            continue

        conf = mol_copy.GetConformer()
        n_atoms = mol_copy.GetNumAtoms()
        lines = [str(n_atoms), ""]
        for j in range(n_atoms):
            atom = mol_copy.GetAtomWithIdx(j)
            symb = atom.GetSymbol()
            pos = conf.GetAtomPosition(j)
            lines.append(f"{symb} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}")
        xyz = "\n".join(lines)
        results.append((xyz, energy))

    results.sort(key=lambda x: x[1])
    return results


def _boltzmann_weights(
    energies: list[float],
    temperature: float = _BOLTZMANN_TEMP,
) -> list[float]:
    """Compute Boltzmann weights from UFF energies.

    Physical justification: The Boltzmann factor exp(-E/kT) gives the
    relative probability of each conformer at temperature T. Conformers
    with energy > 5 kcal/mol above the minimum have negligible weight
    (< 0.02% at 298K) and are effectively excluded.

    Args:
        energies: List of UFF energies in kcal/mol.
        temperature: Temperature in Kelvin (default 298.15 K).

    Returns:
        List of normalised Boltzmann weights summing to 1.0.
    """
    if not energies:
        return []
    e_min = min(energies)
    boltz = [
        math.exp(-(e - e_min) / (_R_GAS * temperature))
        for e in energies
    ]
    total = sum(boltz)
    if total <= 0.0:
        return [1.0 / len(energies)] * len(energies)
    return [w / total for w in boltz]


def _generate_xyz_geometry_optimized(mol: Chem.RWMol) -> str:
    """Fallback XYZ generation using distance geometry without ETKDG."""
    from rdkit.Chem import AllChem, rdDistGeom

    mol = Chem.RWMol(mol)
    mol.UpdatePropertyCache()
    with contextlib.suppress(Exception):
        mol = Chem.AddHs(mol)

    params = rdDistGeom.ETKDGv3()
    params.randomSeed = 42  # type: ignore[assignment]
    params.useRandomCoords = True  # type: ignore[assignment]
    result = AllChem.EmbedMolecule(mol, params)
    if result != 0:
        with contextlib.suppress(Exception):
            AllChem.EmbedMolecule(mol, rdDistGeom.ETKDGv3())

    with contextlib.suppress(Exception):
        AllChem.UFFOptimizeMolecule(mol, maxIters=200)

    conf = mol.GetConformer()
    n_atoms = mol.GetNumAtoms()
    lines = [str(n_atoms), ""]
    for i in range(n_atoms):
        atom = mol.GetAtomWithIdx(i)
        symb = atom.GetSymbol()
        pos = conf.GetAtomPosition(i)
        lines.append(f"{symb} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}")
    return "\n".join(lines)


def _run_xtb(xyz_content: str, workdir: str | None = None) -> dict[str, float] | None:
    """Run xTB single-point calculation and parse HOMO/LUMO from output.

    Uses the module-level cached binary path and shared temp workspace
    to avoid per-call binary discovery and repeated temp dir creation.
    """
    if _XTB_BIN is None:
        return None
    if workdir is None:
        base = _XTB_BASE_TEMP or tempfile.gettempdir()
        workdir = tempfile.mkdtemp(dir=base, prefix="mol_")

    xyz_path = os.path.join(workdir, "input.xyz")
    with open(xyz_path, "w") as f:
        f.write(xyz_content)

    try:
        result = subprocess.run(
            [_XTB_BIN, "--gfn", "2", "--sp", xyz_path],
            cwd=workdir,
            capture_output=True, text=True, timeout=120,
        )
        return _parse_xtb_output(result.stdout)
    except (subprocess.TimeoutExpired, subprocess.CalledProcessError, OSError) as exc:
        logger.debug("xTB run failed: %s", exc)
        return None


def run_xtb_batch(
    xyz_list: list[str], max_workers: int = 4
) -> list[dict[str, float] | None]:
    """Run multiple xTB single-point calculations in parallel.

    Uses a ThreadPoolExecutor to overlap subprocess I/O. Subprocess calls
    release the GIL, so threading is effective for xTB batch execution
    without the overhead of process pool serialization.

    Args:
        xyz_list: List of XYZ-format molecular geometry strings.
        max_workers: Maximum parallel xTB processes (default 4).

    Returns:
        List of result dicts in the same order as xyz_list. Each entry is
        None if xTB failed or is unavailable.
    """
    if _XTB_BIN is None:
        return [None] * len(xyz_list)

    base = _XTB_BASE_TEMP or tempfile.gettempdir()
    workdirs = [
        tempfile.mkdtemp(dir=base, prefix=f"batch_{i}_")
        for i in range(len(xyz_list))
    ]

    results: list[dict[str, float] | None] = [None] * len(xyz_list)
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as pool:
        future_map: dict[concurrent.futures.Future[dict[str, float] | None], int] = {
            pool.submit(_run_xtb, xyz, wd): i
            for i, (xyz, wd) in enumerate(zip(xyz_list, workdirs))
        }
        for future in concurrent.futures.as_completed(future_map):
            idx = future_map[future]
            try:
                results[idx] = future.result()
            except Exception as exc:
                logger.debug("xTB batch item %d failed: %s", idx, exc)
                results[idx] = None

    return results


_XTB_HOMO_RE = re.compile(r"HOMO\s*:\s*([-+]?\d+\.?\d*)\s*eV")
_XTB_LUMO_RE = re.compile(r"LUMO\s*:\s*([-+]?\d+\.?\d*)\s*eV")


def _parse_xtb_output(output: str) -> dict[str, float] | None:
    """Parse xTB output text for HOMO, LUMO, and dipole moment."""
    homo_match = _XTB_HOMO_RE.search(output)
    lumo_match = _XTB_LUMO_RE.search(output)

    if homo_match and lumo_match:
        homo = float(homo_match.group(1))
        lumo = float(lumo_match.group(1))
        logger.info("QuantumOracle (xTB): HOMO=%.3f eV, LUMO=%.3f eV", homo, lumo)
        return {
            "homo_eV": homo,
            "lumo_eV": lumo,
            "dipole_D": 0.0,
        }

    logger.debug("Could not parse HOMO/LUMO from xTB output")
    return None


# ---------------------------------------------------------------------------
# Topological Orbital Model (TOM) — Non-linear Fallback for HOMO/LUMO
# ---------------------------------------------------------------------------
# Based on Hueckel Molecular Orbital (HMO) theory and the particle-in-a-box:
#   - The pi-electron system defines the frontier orbital energy scale
#   - Conjugation length L determines the HOMO-LUMO gap: DeltaE ∝ 1/L²
#   - Heteroatoms perturb the energy via electronegativity differences
#   - The model is non-linear in molecular topology (not fragment-additive)


def _longest_conjugation_path(mol: Chem.Mol) -> int:
    """Find the longest conjugated pi-system in a molecule.

    Returns the number of conjugated atoms in the longest continuous
    conjugated path.
    """
    visited: set[int] = set()
    max_path = 0

    def _dfs(atom_idx: int, path_len: int) -> None:
        nonlocal max_path
        visited.add(atom_idx)
        max_path = max(max_path, path_len)
        atom = mol.GetAtomWithIdx(atom_idx)
        for neighbor in atom.GetNeighbors():
            n_idx = neighbor.GetIdx()
            if n_idx not in visited and _is_conjugated_bond(mol, atom_idx, n_idx):
                _dfs(n_idx, path_len + 1)
        visited.discard(atom_idx)

    for atom in mol.GetAtoms():
        if atom.GetIsAromatic() or atom.GetDegree() > 0:
            _dfs(atom.GetIdx(), 1)

    return max_path


def _is_conjugated_bond(mol: Chem.Mol, i: int, j: int) -> bool:
    """Check if bond between atoms i and j is conjugated."""
    bond = mol.GetBondBetweenAtoms(i, j)
    if bond is None:
        return False
    if bond.GetIsConjugated():
        return True
    bond_type = bond.GetBondType()
    if bond_type in (Chem.BondType.DOUBLE, Chem.BondType.TRIPLE, Chem.BondType.AROMATIC):
        return True
    a1 = mol.GetAtomWithIdx(i)
    a2 = mol.GetAtomWithIdx(j)
    return bool(a1.GetIsAromatic() or a2.GetIsAromatic())


def _is_cross_conjugated(mol: Chem.Mol) -> bool:
    """Check if molecule contains a cross-conjugated pi system.

    Physical basis: Cross-conjugation occurs when a conjugated atom has >2
    conjugated neighbors with at least 2 of those being non-oxygen (carbon)
    conjugated substituents. This excludes normal resonance in esters and
    carbonates (O-C(=O)-O) where oxygen lone-pair donation creates partial
    double-bond character but does NOT disrupt linear pi-delocalisation.
    True cross-conjugation (e.g., divinyl ketone C=CC(=O)C=C, benzophenone
    O=C(c1ccccc1)c1ccccc1) branches the pi system, which the 1D
    particle-in-a-box model overestimates.

    Returns:
        True if any atom has >2 conjugated neighbors with >=2 non-oxygen.
    """
    for atom in mol.GetAtoms():
        n_conj = 0
        n_conj_carbon = 0
        for nb in atom.GetNeighbors():
            if _is_conjugated_bond(mol, atom.GetIdx(), nb.GetIdx()):
                n_conj += 1
                if nb.GetAtomicNum() == 6:
                    n_conj_carbon += 1
        if n_conj > 2 and n_conj_carbon >= 2:
            return True
    return False


# Heteroatom perturbation parameters for the Topological Orbital Model (TOM).
# Each entry: (atomic_num, pi_electrons, ew_flag, ed_flag, is_aromatic_ed)
_ATOM_PERTURBATIONS: list[tuple[int, int, int, int, bool]] = [
    (6, 1, 0, 0, False),    # aromatic carbon
    (7, 1, 1, 0, False),    # non-aromatic N (EW)
    (7, 1, 0, 1, True),     # aromatic N (ED)
    (8, 2, 1, 0, False),    # oxygen
    (9, 0, 1, 0, False),    # fluorine
    (16, 2, 1, 0, False),   # sulfur
    (15, 1, 1, 0, False),   # phosphorus
]


def _count_heteroatom_perturbations(mol: Chem.Mol) -> tuple[int, int, int]:
    """Count electron-withdrawing (EW) and electron-donating (ED) heteroatoms
    in conjugated positions, and total pi-electrons.

    Uses a data-driven lookup table for heteroatom perturbation parameters
    instead of a long if/elif chain.

    Returns:
        (n_ew, n_ed, n_pi_electrons)
    """
    n_ew = 0
    n_ed = 0
    n_pi = 0

    for atom in mol.GetAtoms():
        z = atom.GetAtomicNum()
        if not (atom.GetIsAromatic() or atom.GetDegree() > 0):
            continue
        for az, pi, ew, ed, aromatic_ed in _ATOM_PERTURBATIONS:
            if z != az:
                continue
            if aromatic_ed:
                if atom.GetIsAromatic():
                    n_ed += ed
                else:
                    n_ew += 1
            else:
                n_ew += ew
                n_ed += ed
            n_pi += pi
            break

    return n_ew, n_ed, n_pi


def _topological_sanity_l(mol: Chem.Mol, L: int) -> int:
    """Cap effective conjugation length if the molecule lacks 3D structural support.

    Physical justification: The particle-in-a-box gap (ΔE ∝ 1/L²) assumes a
    perfectly planar, rigid conjugated system. Real molecules with long
    conjugation paths (L > 12) require structural support — sp3 carbons,
    branching, or ring fusion — to maintain planarity against torsional
    disorder. A molecule with a long linear polyene chain but negligible sp3
    character (sp3 fraction < 0.10) will have severe torsional disorder that
    breaks conjugation, making the 1/L² gap scaling invalid. The effective
    conjugation length is capped at 12 in such cases, which corresponds to
    a gap floor of ~0.26 eV — realistically the minimum gap for any organic
    electrolyte molecule in solution.
    """
    if L <= 12:
        return L
    n_c = sum(a.GetAtomicNum() == 6 for a in mol.GetAtoms())
    n_sp3 = sum(
        a.GetAtomicNum() == 6 and a.GetHybridization() == Chem.HybridizationType.SP3
        for a in mol.GetAtoms()
    )
    if n_c == 0:
        return min(L, 12)
    sp3_frac = n_sp3 / n_c
    if sp3_frac < 0.10:
        return 12
    return L


# σ* LUMO corrections for S/P=O groups in non-conjugated molecules.
# Physical basis: S=O and P=O bonds have low-lying σ* orbitals from
# d-orbital participation that lower LUMO significantly below what the
# inductive EW perturbation predicts. Each correction is applied once
# if the group is present (not per-match, to avoid double counting).
_SIGMA_STAR_LUMO: list[tuple[Chem.Mol, str, float]] = [
    (Chem.MolFromSmarts("S(=O)(=O)"), "sulfone", -0.70),
    (Chem.MolFromSmarts("[SX3](=O)"), "sulfoxide", -0.50),
    (Chem.MolFromSmarts("[PX4](=O)"), "phosphate", -0.30),
]

# Pre-compiled SMARTS for phosphate HOMO correction (P=O in phosphates)
_PHOSPHATE_PATTERN: Chem.Mol = Chem.MolFromSmarts("[PX4](=O)")


def _count_aromatic_rings(mol: Chem.Mol) -> int:
    """Count number of aromatic rings (all atoms in ring are aromatic)."""
    ring_info = mol.GetRingInfo()
    n_aromatic = 0
    for ring in ring_info.AtomRings():
        if all(mol.GetAtomWithIdx(i).GetIsAromatic() for i in ring):
            n_aromatic += 1
    return n_aromatic


def _wiener_index(mol: Chem.Mol) -> float:
    """Compute the Wiener index (sum of all-pairs shortest path distances).

    Physical basis: The Wiener index measures molecular compactness. A lower
    Wiener index (more compact) correlates with stronger interatomic
    interactions and stabilised frontier orbitals. This is a closed-form
    topological descriptor — no regression weights needed.
    """
    n = mol.GetNumAtoms()
    if n <= 1:
        return 0.0
    total = 0
    from rdkit.Chem import rdmolops
    matrix = rdmolops.GetDistanceMatrix(mol)
    for i in range(n):
        for j in range(i + 1, n):
            total += int(matrix[i][j])
    return float(total)


def _apply_wiener_compactness(mol: Chem.Mol, L: int) -> int:
    """Adjust conjugation length L based on Wiener-index molecular compactness.

    Physical basis: Compact molecules (low Wiener index per atom) have stronger
    through-space orbital overlap, effectively shortening the conjugation path.
    L is reduced by up to 30% based on compactness = 1 - W/W_linear.
    """
    n_atoms = mol.GetNumAtoms()
    w = _wiener_index(mol)
    if n_atoms <= 1:
        return L
    w_linear = n_atoms * (n_atoms * n_atoms - 1) / 6.0
    if w_linear <= 0:
        return L
    compactness = max(0.0, 1.0 - w / w_linear)
    L = int(L * (1.0 - 0.30 * compactness))
    return max(L, 2)


def _conjugated_bond_deviation(
    mol: Chem.Mol, conf: Chem.Conformer, i: int, j: int
) -> float | None:
    """Measure the torsional deviation from planarity for a conjugated bond (i-j).

    Finds flanking conjugated neighbors on both sides of the bond and returns
    the minimum angular deviation from 0° or 180° (planar). Returns None if
    suitable flanking atoms cannot be found.
    """
    from rdkit.Chem import rdMolTransforms

    ai = mol.GetAtomWithIdx(i)
    aj = mol.GetAtomWithIdx(j)
    ni = None
    for nb in ai.GetNeighbors():
        n_idx = nb.GetIdx()
        if n_idx != j and _is_conjugated_bond(mol, i, n_idx):
            ni = n_idx
            break
    nj = None
    for nb in aj.GetNeighbors():
        n_idx = nb.GetIdx()
        if n_idx != i and _is_conjugated_bond(mol, j, n_idx):
            nj = n_idx
            break
    if ni is None or nj is None:
        return None
    try:
        dihedral = abs(rdMolTransforms.GetDihedralDeg(conf, ni, i, j, nj))
        return min(dihedral, abs(180.0 - dihedral))
    except Exception:
        return None


def _apply_torsional_strain_penalty(mol: Chem.Mol, L: int) -> int:
    """Reduce effective conjugation length L if conjugated system is non-planar.

    Physical basis: The particle-in-a-box model assumes a perfectly planar
    conjugated system. Torsional strain (dihedral > 30°) between adjacent
    conjugated atoms breaks pi-orbital overlap, effectively shortening the
    conjugation path. This prevents false-positive narrow gaps for sterically
    hindered conjugated molecules (e.g., bulky biphenyl derivatives).

    Uses RDKit's ETKDGv3 conformer generation with useRandomCoords and UFF
    relaxation (maxIts=500) to escape local minima for sterically hindered
    molecules. For each conjugated bond with flanking neighbors, the dihedral
    angle is measured. If any exceeds 30 deg, L is reduced by 30% (floor 2).
    """
    if L <= 2:
        return L
    from rdkit.Chem import AllChem

    mol_copy = Chem.RWMol(mol)
    mol_copy.UpdatePropertyCache()
    try:
        mol_copy = Chem.AddHs(mol_copy)
        params = AllChem.ETKDGv3()
        params.randomSeed = 42
        params.useRandomCoords = True
        result = AllChem.EmbedMolecule(mol_copy, params)
        if result != 0:
            return L
        AllChem.UFFOptimizeMolecule(mol_copy, maxIters=500)
        conf = mol_copy.GetConformer()
    except Exception:
        return L

    max_deviation = 0.0
    for bond in mol.GetBonds():
        if not bond.GetIsConjugated():
            continue
        deviation = _conjugated_bond_deviation(
            mol, conf, bond.GetBeginAtomIdx(), bond.GetEndAtomIdx()
        )
        if deviation is not None and deviation > max_deviation:
            max_deviation = deviation

    if max_deviation > 30.0:
        L = max(2, int(L * 0.7))
    return L


def _apply_peierls_damping(L: int) -> int:
    """Apply Peierls distortion damping to prevent 1/L² gap collapse for L > 8.

    Physical basis: Long polyenes undergo bond-length alternation that opens a
    finite gap (ΔE ≈ 1.5-2.0 eV) even for infinite chains. The closed-form
    saturation L_eff = 8 + (L-8)/(1+0.10·(L-8)) preserves moderate-L behavior.
    """
    if L <= 8:
        return L
    alpha = 0.10
    L = int(8 + (L - 8) / (1.0 + alpha * (L - 8)))
    return max(L, 2)


def _compute_tom_base_energies(L: int) -> tuple[float, float]:
    """Compute base HOMO/LUMO from conjugation length using particle-in-a-box.

    The gap scales as ΔE = 37.6 / L² (eV). For L < 3, uses fixed base values.
    Base offsets calibrated against orbital_calibration.json (45 references).
    """
    base_homo = -6.8
    base_lumo = 1.5
    if L >= 3:
        gap = 37.6 / (L * L)
        mid = (base_homo + base_lumo) / 2.0
        return mid - gap / 2.0, mid + gap / 2.0
    return base_homo, base_lumo


def _apply_heteroatom_perturbations(n_ew: int, n_ed: int, homo: float, lumo: float) -> tuple[float, float]:
    """Apply Hueckel-like heteroatom corrections to HOMO/LUMO.

    Electron-withdrawing groups stabilise both orbitals; electron-donating
    groups destabilise. EW coefficient -0.32, LUMO EW scaling 0.35 (HOMO-biased).
    """
    ew_shift = -0.32 * n_ew
    ed_shift = 0.12 * n_ed
    return homo + ew_shift + ed_shift, lumo + ew_shift * 0.35 + ed_shift * 0.5


def _apply_fluorine_correction(mol: Chem.Mol, homo: float, lumo: float) -> tuple[float, float]:
    """Apply fluorine inductive withdrawal correction (-0.15 eV per F)."""
    n_f = sum(a.GetAtomicNum() == 9 for a in mol.GetAtoms())
    f_shift = -0.15 * n_f
    return homo + f_shift, lumo + f_shift


def _apply_aromatic_stabilization(mol: Chem.Mol, homo: float, lumo: float) -> tuple[float, float]:
    """Apply aromatic ring stabilization (-0.25 HOMO, -0.15 LUMO per ring).

    Physical basis: Cyclic delocalisation (resonance energy ~1.5 eV for benzene)
    stabilises both frontier orbitals beyond 1-D PIB confinement.
    """
    n_arom = _count_aromatic_rings(mol)
    return homo + -0.25 * n_arom, lumo + -0.15 * n_arom


def _apply_nitrile_correction(mol: Chem.Mol, lumo: float) -> float:
    """Apply nitrile C≡N π* LUMO lowering (-0.70 eV per nitrile).

    Physical basis: The C≡N π* orbital is ~0.7-1.0 eV lower than the general
    N perturbation predicts.
    """
    n_nitrile = len(mol.GetSubstructMatches(NITRILE_PATTERN))
    return lumo + -0.70 * n_nitrile


def _apply_phosphate_correction(mol: Chem.Mol, homo: float) -> float:
    """Apply phosphate HOMO correction (+0.50 per P=O) for σ-only P-O-C bonds.

    Physical basis: σ-only P-O-C oxygen EW contributions are over-counted;
    +0.50 corrects ~2/3 of the over-counting (~0.96 eV for trialkyl phosphates).
    """
    n_phosphate = len(mol.GetSubstructMatches(_PHOSPHATE_PATTERN))
    return homo + 0.50 * n_phosphate


def _apply_sigma_star_correction(mol: Chem.Mol, L: int, lumo: float) -> float:
    """Apply σ* LUMO correction for non-conjugated S/P=O groups (d-orbital participation).

    Physical basis: S=O and P=O bonds have low-lying σ* orbitals from d-orbital
    participation that lower LUMO by 0.3-0.7 eV. Applied only for L<3 where the
    LUMO is σ* (not π*) character.
    """
    if L >= 3:
        return lumo
    for _spattern, _sname, _sshift in _SIGMA_STAR_LUMO:
        if len(mol.GetSubstructMatches(_spattern)) > 0:
            lumo += _sshift
    return lumo


def _apply_cross_conjugation_penalty(mol: Chem.Mol, lumo: float) -> float:
    """Apply cross-conjugation penalty (+0.30 eV to LUMO).

    Physical basis: Cross-conjugated systems disrupt pi-delocalisation; the
    1D particle-in-a-box overestimates the gap. Widening by +0.30 eV corrects
    for this overestimation (e.g., divinyl ketone, benzophenone).
    """
    if _is_cross_conjugated(mol):
        return lumo + 0.30
    return lumo


def predict_tom_orbitals(mol: Chem.Mol) -> tuple[float, float]:
    """Predict HOMO/LUMO using the Topological Orbital Model (TOM).

    The model estimates frontier orbital energies from:
        1. Longest conjugation path length (L)
        2. HOMO-LUMO gap from particle-in-a-box: ΔE ∝ 1/L²
        3. Heteroatom perturbations (electron-withdrawing/donating)
        4. Aromatic ring stabilization (−0.25 eV HOMO, −0.15 eV LUMO per ring)
        5. Wiener-index compactness adjustment (factor 0.30)
        6. σ* LUMO correction for S/P=O groups in non-conjugated molecules
        7. Phosphate HOMO correction (+0.50 per P=O) for σ-only P-O-C bonds
        8. Base offset calibrated to 45 electrolyte molecules from DFT references.
        9. Cross-conjugation penalty for branched pi-systems.

    Returns:
        (homo_eV, lumo_eV)
    """
    L = _longest_conjugation_path(mol)
    L = max(L, 2)
    L = _topological_sanity_l(mol, L)
    L = _apply_wiener_compactness(mol, L)
    L = _apply_torsional_strain_penalty(mol, L)
    L = _apply_peierls_damping(L)

    n_ew, n_ed, _ = _count_heteroatom_perturbations(mol)
    homo, lumo = _compute_tom_base_energies(L)
    homo, lumo = _apply_heteroatom_perturbations(n_ew, n_ed, homo, lumo)
    homo, lumo = _apply_fluorine_correction(mol, homo, lumo)
    homo, lumo = _apply_aromatic_stabilization(mol, homo, lumo)
    lumo = _apply_nitrile_correction(mol, lumo)
    homo = _apply_phosphate_correction(mol, homo)
    lumo = _apply_sigma_star_correction(mol, L, lumo)
    lumo = _apply_cross_conjugation_penalty(mol, lumo)

    return homo, lumo


# ---------------------------------------------------------------------------
# Domain of Applicability (DoA) — TOM-specific epistemic uncertainty
# ---------------------------------------------------------------------------
# Physical justification: The TOM is calibrated against molecules with moderate
# conjugation (L ≤ 12) and reasonable pi-electron counts. Molecules with extreme
# conjugation paths lacking sp3 structural support, or excessive pi-systems,
# fall outside the TOM calibration domain. The particle-in-a-box model assumes
# a planar rigid system; long conjugation without sp3 breaks planarity, and
# excessive pi-electrons violate the single-particle HMO approximation.
# These are closed-form heuristics — no ML involved.


def compute_quantum_domain_penalty(ctx: MoleculeContext) -> tuple[float, str]:
    """Compute domain-of-applicability penalty for TOM predictions.

    Penalises molecules with topological features that fall outside the
    TOM calibration domain (conjugation > 12 without sp3 support, excessive
    pi-electrons).

    Returns:
        (penalty_multiplier, reason_string)
        Multiplier in [0.70, 1.0]; 1.0 = fully within domain.
    """
    mol = ctx.mol
    reasons: list[str] = []
    penalty = 1.0

    L = _longest_conjugation_path(mol)
    if L > 12:
        n_c = sum(a.GetAtomicNum() == 6 for a in mol.GetAtoms())
        n_sp3 = sum(
            a.GetAtomicNum() == 6 and a.GetHybridization() == Chem.HybridizationType.SP3
            for a in mol.GetAtoms()
        )
        sp3_frac = n_sp3 / max(n_c, 1)
        if sp3_frac < 0.15:
            penalty *= 0.70
            reasons.append(
                f"long conjugation (L={L}) without sp3 support (sp3_frac={sp3_frac:.2f})"
            )

    _, _, n_pi = _count_heteroatom_perturbations(mol)
    if n_pi > 24:
        penalty *= 0.80
        reasons.append(f"excessive pi-system (n_pi={n_pi}) outside TOM calibration")

    return penalty, "; ".join(reasons) if reasons else "within domain"


# ---------------------------------------------------------------------------
# QuantumOracle — Unified interface for xTB + TOM fallback
# ---------------------------------------------------------------------------


class QuantumOracle:
    """Quantum-chemical oracle for frontier orbital energies.

    Two-tier evaluation:
       1. xTB (GFN2-xTB) via subprocess — preferred, real QM
       2. Topological Orbital Model (TOM) — conjugation-aware fallback

    When xTB is available, generates multiple conformers via ETKDGv3,
    UFF-optimises each, computes Boltzmann weights, and runs xTB on the
    top-3 lowest-energy conformers. The final HOMO/LUMO is the
    Boltzmann-weighted average, and ``quantum_confidence`` reports the
    conformer energy variance as a proxy for prediction stability.

    Results are cached by SMILES to avoid redundant computation.
    """

    def __init__(
        self,
        use_xtb: bool = True,
        n_conformers: int = _N_CONFORMERS,
        n_top_conformers: int = _N_TOP_CONFORMERS,
    ) -> None:
        self._use_xtb = use_xtb and _HAS_XTB
        self._n_conformers = n_conformers
        self._n_top_conformers = n_top_conformers
        self._cache: dict[str, dict[str, float]] = {}
        self._n_xtb_calls = 0
        self._n_tom_calls = 0

        if use_xtb and not _HAS_XTB:
            logger.info("QuantumOracle: xTB binary not found — using TOM fallback.")
        elif self._use_xtb:
            logger.info("QuantumOracle: xTB backend ENABLED.")

    @property
    def method(self) -> str:
        return "xTB (GFN2-xTB)" if self._use_xtb else "TOM (Topological Orbital Model)"

    @property
    def n_quantum_calls(self) -> int:
        return self._n_xtb_calls + self._n_tom_calls

    @staticmethod
    def _run_xtb_flat(conformers: list[tuple[str, float]], n_top: int) -> tuple[list[dict[str, float]], list[float]]:
        """Run xTB on top N conformers, return (results, energies)."""
        top = conformers[:n_top]
        results: list[dict[str, float]] = []
        energies: list[float] = []
        for xyz, uff_energy in top:
            xtb_result = _run_xtb(xyz)
            if xtb_result is not None:
                results.append(xtb_result)
                energies.append(uff_energy)
        return results, energies

    @staticmethod
    def _boltzmann_average(xtb_results: list[dict[str, float]], energies: list[float]) -> dict[str, float]:
        """Compute Boltzmann-weighted average HOMO/LUMO/dipole from xTB results."""
        weights = _boltzmann_weights(energies)
        homo_w = sum(w * r["homo_eV"] for w, r in zip(weights, xtb_results, strict=False))
        lumo_w = sum(w * r["lumo_eV"] for w, r in zip(weights, xtb_results, strict=False))
        dipole_w = sum(w * r.get("dipole_D", 0.0) for w, r in zip(weights, xtb_results, strict=False))
        homo_vals = [r["homo_eV"] for r in xtb_results]
        conformer_variance = float(np.std(homo_vals, ddof=1)) if len(homo_vals) > 1 else 0.0
        conf = "xtb_high" if conformer_variance < 0.15 else "xtb"
        return {
            "homo_eV": homo_w,
            "lumo_eV": lumo_w,
            "dipole_D": dipole_w,
            "conformer_variance": round(conformer_variance, 4),
            "quantum_confidence": conf,
        }

    def _evaluate_with_boltzmann(self, mol: Chem.Mol) -> dict[str, float]:
        """Evaluate using Boltzmann-weighted multi-conformer averaging.

        Generates up to N conformers, runs xTB on the top-3 lowest UFF
        energy conformers, and computes Boltzmann-weighted average
        HOMO/LUMO. Returns a quantum_confidence metric based on the
        standard deviation of HOMO across conformers.
        """
        conformers = _generate_multi_xyz(mol, n_conformers=self._n_conformers)
        if not conformers:
            result = _run_xtb(_generate_xyz(mol))
            if result is not None:
                self._n_xtb_calls += 1
                result["quantum_confidence"] = "xtb"
                return result
            return self._evaluate_tom(mol)

        xtb_results, energies = self._run_xtb_flat(conformers, self._n_top_conformers)

        if not xtb_results:
            self._n_xtb_calls += 1
            result = _run_xtb(conformers[0][0])
            if result is not None:
                self._n_xtb_calls += 1
                result["quantum_confidence"] = "xtb"
                return result
            return self._evaluate_tom(mol)

        self._n_xtb_calls += len(xtb_results)

        if len(xtb_results) == 1:
            result = dict(xtb_results[0])
            result["quantum_confidence"] = "xtb"
            return result

        return self._boltzmann_average(xtb_results, energies)

    def _evaluate_tom(self, mol: Chem.Mol) -> dict[str, float]:
        """Fallback TOM evaluation."""
        homo, lumo = predict_tom_orbitals(mol)
        L = _longest_conjugation_path(mol)
        n_rings = mol.GetRingInfo().NumRings()
        conf_var = 0.0
        result: dict[str, float] = {
            "homo_eV": homo,
            "lumo_eV": lumo,
            "dipole_D": 0.0,
            "conformer_variance": conf_var,
            "quantum_confidence": "tom_high" if L <= 8 and n_rings <= 2 else "tom_low",
        }
        return result

    def evaluate(self, mol: Chem.Mol) -> dict[str, float]:
        smiles = Chem.MolToSmiles(mol)
        if smiles in self._cache:
            return dict(self._cache[smiles])

        if self._use_xtb:
            result = self._evaluate_with_boltzmann(mol)
            if result is not None and "conformer_variance" in result:
                self._cache[smiles] = result
                return dict(result)
            logger.warning("QuantumOracle: xTB calculation failed — falling back to TOM.")

        result = self._evaluate_tom(mol)
        self._n_tom_calls += 1
        self._cache[smiles] = result
        return dict(result)

    def clear_cache(self) -> None:
        self._cache.clear()

    def get_cache_size(self) -> int:
        return len(self._cache)
